# Auto-generated from Sputter Error Code.docx
DEFAULT_CODES = {'E101': {'cause': 'EOF while reading (클라이언트가 요청 중 연결을 끊음)', 'fix': '클라이언트/네트워크 안정성 확인, 요청 전송 후 소켓을 바로 닫지 않도록 수정, keepalive/timeout 조정'},
 'E102': {'cause': 'Unsupported protocol version (프로토콜 버전 불일치)', 'fix': 'client/server 양쪽의 protocol.py 버전/HEADER_STRUCT를 동일하게 맞춤(버전 필드 포함)'},
 'E103': {'cause': 'Invalid header size/format (헤더 파싱 실패/깨짐)', 'fix': '클라이언트의 pack/unpack(헤더 16바이트, 길이 필드) 일치 확인, endian/struct 포맷 통일'},
 'E104': {'cause': 'Invalid JSON body (요청 바디 JSON 디코딩 실패)', 'fix': 'client가 UTF-8 JSON으로 보내는지 확인, body_len과 실제 바디 길이가 맞는지 확인'},
 'E105': {'cause': 'Missing command in request', 'fix': '요청 JSON에 command 키를 반드시 포함(예: {"command":"VACUUM_ON", ...})'},
 'E106': {'cause': 'Unknown command', 'fix': 'host/router.py에 등록된 커맨드명과 client 커맨드명을 일치(오탈자/대소문자 포함)'},
 'E107': {'cause': 'Response serialization failed (응답 JSON 변환 실패)', 'fix': '응답 dict 안에 bytes/비직렬화 객체가 들어가지 않도록 수정(detail은 문자열/숫자/dict)'},
 'E108': {'cause': 'Request too large (과도한 body_len/비정상 패킷)', 'fix': 'client에서 body 크기 제한, 서버에서 body_len 상한 체크(권장) 추가'},
 'E109': {'cause': 'Connection reset/broken pipe (응답 전송 중 연결 끊김)', 'fix': 'client가 응답 받기 전에 소켓을 닫지 않게 수정, 재시도 로직/ACK 설계'},
 'E110': {'cause': 'Handler crash (핸들러 내부 예외로 요청 처리 중단)', 'fix': '서버 로그 확인 후 해당 command 핸들러에 예외를 AppError로 정규화'},
 'E201': {'cause': 'ch는 1 또는 2만 허용합니다', 'fix': 'client payload의 ch 값을 1/2로만 전송, 문자열이면 int 변환해서 전달'},
 'E202': {'cause': 'recipe가 비어 있습니다 (CSV 경로 또는 레시피 문자열 필요)', 'fix': 'payload에 recipe_path 또는 recipe_string(허용 형태)을 포함'},
 'E203': {'cause': 'Chamber CHx runtime not ready', 'fix': '프로그램에서 runtime 초기화 완료 후 요청(초기 connect/preflight 완료 확인)'},
 'E204': {'cause': 'Plasma Cleaning runtime not ready', 'fix': 'plasma runtime 초기화 완료 후 요청'},
 'E205': {'cause': '명령 불가 — 공정 실행 중 (runtime_state busy)', 'fix': '공정 종료 후 재시도'},
 'E206': {'cause': '다른 start 요청이 이미 처리 중입니다 (중복 start 가드)', 'fix': 'client에서 start 요청을 단발로 보내고, 응답/상태 확인 후 다음 요청'},
 'E207': {'cause': 'CSV 파일을 찾을 수 없습니다: path', 'fix': 'NAS 제외하더라도 로컬 경로/상대경로 오타 확인, 실행 폴더 기준 경로인지 확인'},
 'E208': {'cause': 'CSV에 데이터 행이 없습니다 / 공정 데이터가 없습니다', 'fix': 'CSV 형식/헤더/내용 확인(빈 파일/헤더만 존재)'},
 'E209': {'cause': '지원하지 않는 레시피 형식입니다 (CSV 경로만 허용)', 'fix': '현재 코드가 CSV path만 허용하는 runtime(start_with_recipe_string) 정책을 따름'},
 'E210': {'cause': 'preflight timeout (프리플라이트에 도달하지 못함)', 'fix': '쿨다운/가드 조건을 해제하거나, preflight 조건을 만족하도록 장비 상태를 준비'},
 'E211': {'cause': '공정 시퀀스 검증 실패', 'fix': 'process_controller의 Step 구성(DELAY 병렬 금지 등) 규칙 위반 여부 확인'},
 'E212': {'cause': 'unknown kind (runtime_state kind 정규화 실패)', 'fix': 'runtime_state에 넘기는 kind 문자열을 정의된 값으로만 사용'},
 'E213': {'cause': '알 수 없는 Action', 'fix': '레시피 Action명이 controller/process_controller.py에 정의된 것만 사용'},
 'E214': {'cause': 'DELAY 액션은 duration이 필요합니다', 'fix': 'DELAY에는 duration_sec(또는 duration) 필드를 반드시 포함'},
 'E215': {'cause': 'DELAY는 병렬 블록에 포함할 수 없습니다', 'fix': '병렬(parallel) 블록 안에 DELAY를 넣지 않도록 레시피 구성 변경'},
 'E216': {'cause': 'PLC_CMD params 형식 오류', 'fix': 'PLC_CMD는 (name:str, on:any[, ch:int]) 형태로 전달'},
 'E217': {'cause': 'MFC_CMD params 형식 오류', 'fix': 'MFC_CMD는 (cmd:str, args:dict) 형태로 전달'},
 'E218': {'cause': 'OES_RUN params 형식 오류', 'fix': 'OES_RUN은 (process_time_sec:float, integration_ms:int) 형태로 전달'},
 'E219': {'cause': 'DC_PULSE_START value(타깃 파워)가 필요합니다', 'fix': 'DC_PULSE_START에는 목표 파워 value를 넣어서 전달'},
 'E220': {'cause': 'RF_PULSE_START value(타깃 파워)가 필요합니다', 'fix': 'RF_PULSE_START에도 목표 파워 value 전달'},
 'E221': {'cause': 'DC_PULSE_START params 형식 오류(freq/duty)', 'fix': '(freqkHz|None, duty%|None) 형태 준수'},
 'E222': {'cause': 'RF_PULSE_START params 형식 오류(freq/duty)', 'fix': '(freqkHz|None, duty%|None) 형태 준수(내부에서 Hz로 변환)'},
 'E223': {'cause': 'TSP_targetPressure_edit 가 비어있습니다', 'fix': 'TSP 목표 압력 입력값을 넣고 시작'},
 'E224': {'cause': 'TSP_setCycle_edit 가 비어있습니다', 'fix': 'TSP 반복 횟수 입력'},
 'E225': {'cause': '반복 횟수는 1 이상이어야 합니다', 'fix': 'cycles 값을 1 이상으로 설정'},
 'E301': {'cause': 'START_SPUTTER 불가 — CHx gate가 CLOSED가 아님', 'fix': 'Gate CLOSE 확인 후 시작(소프트웨어/PLC 램프 기준 일치 확인)'},
 'E302': {'cause': 'CHx_GATE_OPEN 불가 — gate interlock FALSE', 'fix': 'PLC의 G_V_x_인터락 신호 확인(실제 인터락 조건/센서 이상/배선/PLC 로직)'},
 'E303': {'cause': '다른 챔버 Gate가 CLOSED가 아님 → Gate OPEN 불가', 'fix': '동시에 두 Gate를 열지 않도록 운용, 상대 챔버 Gate를 먼저 닫고 재시도'},
 'E304': {'cause': 'CHx_GATE_OPEN 실패 — OPEN_LAMP=FALSE (대기 시간 초과)', 'fix': '실제 Gate 구동/센서 확인, OPEN_LAMP 입력 배선/PLC 주소맵 점검, 기구물 걸림 점검'},
 'E305': {'cause': 'CHx_GATE_CLOSE 실패 — CLOSE_LAMP=FALSE (대기 시간 초과)', 'fix': 'CLOSE_LAMP 입력 확인, 구동부/센서/PLC 주소맵 점검'},
 'E306': {'cause': 'Gate 상태 센서 모순(OPEN과 CLOSE가 동시에 TRUE 또는 둘 다 FALSE)', 'fix': '센서/배선/PLC 래더 확인, 소프트웨어에서 “모순이면 즉시 차단” 권장(진공/펌프 동작 금지)'},
 'E307': {'cause': 'Vacuum ON 전 Gate CLOSE 미확인(안전 차단)', 'fix': 'vacuum_on 핸들러에서 gate 상태를 확인하고 CLOSED가 아니면 차단하도록 유지'},
 'E308': {'cause': 'Vacuum OFF 전 Gate CLOSE 미확인(안전 차단)', 'fix': 'vent 중 Gate가 열리면 위험하므로 동일하게 차단 유지'},
 'E309': {'cause': '러핑펌프 OFF 타이머 진행 중 → VACUUM_ON 차단', 'fix': 'L_R_P_OFF_TIMER가 FALSE가 될 때까지 대기 후 재시도(펌프 보호 시퀀스)'},
 'E310': {'cause': 'L_R_V_인터락=FALSE → 러핑밸브 개방 불가', 'fix': '러핑밸브 인터락 조건(도어/게이트/압력 등) 해소 후 재시도'},
 'E311': {'cause': 'L_VENT_인터락=FALSE → 벤트 불가', 'fix': '벤트 인터락 조건 해소(게이트/도어/진공 상태 등)'},
 'E312': {'cause': 'VACUUM_ON 타임아웃(시간 내 VAC_READY && 펌프/밸브 OFF 상태 미도달)', 'fix': '도어/밸브 상태, 펌프 동작, L_VAC_NOT_READY 원인 제거(누설/게이트 미닫힘/배기 불가)'},
 'E313': {'cause': 'VACUUM_OFF 타임아웃(시간 내 ATM TRUE 미도달)', 'fix': 'N2 가스 부족/벤트 밸브/유량 확인, ATM 센서 입력 확인'},
 'E314': {'cause': '4PIN_UP 불가 — L_PIN_인터락=FALSE', 'fix': '핀 인터락 조건 확인(챔버 위치/모터 위치/안전 스위치)'},
 'E315': {'cause': '4PIN_DOWN 불가 — L_PIN_인터락=FALSE', 'fix': '핀 인터락 조건 확인(챔버 위치/모터 위치/안전 스위치)'},
 'E316': {'cause': '4PIN_UP 실패 — 시간 후 L_PIN_UP_LAMP=FALSE', 'fix': '핀 구동부/센서/PLC 입력 주소 확인'},
 'E317': {'cause': '4PIN_DOWN 실패 — 시간 후 L_PIN_DOWN_LAMP=FALSE', 'fix': '핀 구동부/센서/PLC 입력 주소 확인'},
 'E318': {'cause': 'Chuck 위치 이동 타임아웃(MID/DOWN 등 램프 미도달)', 'fix': '모터/리미트/센서/PLC 입력 확인, 기구물 간섭 점검'},
 'E319': {'cause': 'Gate OPEN 상태에서 Vacuum 관련 출력이 켜짐(안전 위반 감지)', 'fix': 'PLC 로직상 상호배제가 없을 수 있음 → 소프트웨어에서 gate open이면 L_R_P/L_R_V 동작 차단, 현장 배선/래더도 함께 점검'},
 'E320': {'cause': 'Gate 상태 읽기 실패(지원하지 않는 CH)', 'fix': 'CH 값 1/2만 사용, 코드에서 지원하지 않는 CH는 즉시 차단 유지'},
 'E321': {'cause': 'Loadlock 상태로 인해 Gate Open 불가(벤트/러핑/ATM 전환 중)', 'fix': 'VACUUM_ON/OFF 전환이 끝난 뒤(러핑펌프/러핑밸브 OFF, 안정화) Gate Open 재시도'},
 'E401': {'cause': 'Modbus TCP 연결 실패', 'fix': 'PLC IP/PORT/네트워크 확인, PLC 전원/통신 상태 확인, timeout 조정'},
 'E402': {'cause': 'Modbus 응답 없음(None)', 'fix': 'PLC 통신 불안정/timeout 과소 가능, polling 과밀 여부 확인(큐 밀림)'},
 'E403': {'cause': 'Modbus Exception 발생', 'fix': 'function code/주소 범위 확인, PLC가 해당 coil/register를 제공하는지 확인'},
 'E404': {'cause': '알 수 없는 주소/이름 (PLC 주소맵 키 오류)', 'fix': 'PLC_COIL_MAP/REG_MAP에 키 추가 또는 client/코드에서 사용하는 키명을 맵과 일치'},
 'E405': {'cause': 'PLC_COIL_MAP에 key 없음 (family/idx 조합 오류)', 'fix': 'power_enable 등 family/index로 만드는 키 규칙을 PLC 맵에 맞게 수정'},
 'E406': {'cause': 'PLC_REG_MAP에 key 없음 (power_write/power_read)', 'fix': '레지스터 맵 키 추가 또는 family/index 규칙 수정'},
 'E407': {'cause': 'name required (PLC set()에 name 누락)', 'fix': 'PLC set 명령에는 name 필수'},
 'E408': {'cause': '지원하지 않는 PLC 논리명/키', 'fix': 'PLC set()에서 허용하는 name/alias만 사용하거나, alias 테이블을 확장'},
 'E409': {'cause': 'gas must be one of {AR,O2,N2,MAIN}', 'fix': '가스 문자열을 해당 집합으로만 전달'},
 'E410': {'cause': '가스가 CHx에 존재하지 않습니다(키 없음)', 'fix': '해당 챔버에 그 가스 코일이 실제로 없거나 맵 누락 → PLC 맵과 장비 구성 일치 확인'},
 'E411': {'cause': 'PLC 주소맵에 로딩센서 키가 없습니다', 'fix': '_get_loading_sensor에서 사용하는 PLC 키를 맵에 추가하거나 센서 기능 비활성 처리'},
 'E412': {'cause': 'read_bit 실패(내부적으로 KeyError/ModbusException 등)', 'fix': '키/통신 상태 확인, 예외는 AppError로 정규화하여 client에 코드로 반환 권장'},
 'E501': {'cause': '장비 연결 타임아웃(목록)', 'fix': 'preflight_connect에서 connect 대상 장비 확인, 장비 전원/통신 설정 점검'},
 'E502': {'cause': '연결 실패: device connect() 반환 실패', 'fix': '해당 장비 IP/COM/포트/드라이버 상태 점검'},
 'E503': {'cause': '상태 확인 시간초과(TSP 등)', 'fix': '센서/장비 응답 지연, timeout 상향 또는 retry/백오프 적용'},
 'E504': {'cause': '안정화 대상 없음(MFC FLOW_ON 등)', 'fix': '안정화 루프 시작 전에 대상 유량/가스 선택을 먼저 수행'},
 'E505': {'cause': 'GAS 안정화 시간 초과', 'fix': '유량이 목표에 도달하지 못함(레귤레이터/밸브/라인 막힘/설정 오류) 점검'},
 'E506': {'cause': 'TSP run timed out', 'fix': '목표 압력/사이클/장비 상태 점검, timeout 상향 가능'},
 'E507': {'cause': 'Chuck/Pin/Gate 램프 대기 타임아웃', 'fix': '기구부 동작/센서/PLC 입력 주소 확인'},
 'E601': {'cause': 'IG read callback is not bound', 'fix': 'plasma_cleaning_runtime에서 ig_read_mTorr 콜백 바인딩 누락 → 런타임 초기화 바인딩 확인'},
 'E602': {'cause': 'IG not bound', 'fix': 'IG 객체가 runtime에 주입/연결되지 않음 → 컨텍스트/의존성 주입 확인'},
 'E603': {'cause': 'IG object does not provide read_pressure()', 'fix': 'IG 구현체에 read_pressure가 없으면 wrapper 추가 또는 사용하는 IG 클래스 교체'},
 'E604': {'cause': 'IG read API not found (main.py)', 'fix': 'IG 읽기 함수명을 코드에서 찾지 못함 → IG 모듈/바인딩 이름 일치'},
 'E605': {'cause': 'IG ON 실패(ensure_on)', 'fix': 'IG 전원/시리얼/통신 확인, SIG 1 동작 확인'},
 'E606': {'cause': 'RDI timeout (IG read_pressure)', 'fix': 'IG 통신 지연/포트 문제 → timeout 상향, 배선/포트 점검'},
 'E607': {'cause': 'IG parse error', 'fix': 'IG 응답 포맷 변경/깨짐 → 파서/프로토콜 확인'},
 'E608': {'cause': 'Base pressure not reached (IG API)', 'fix': '누설/펌프/밸브/게이트 상태 확인, 기준 압력/시간 설정 재검토'},
 'E609': {'cause': 'mfc_gas not bound', 'fix': 'MFC 가스 채널 객체 바인딩 누락 → runtime 초기화에서 주입 확인'},
 'E610': {'cause': 'mfc_pressure not bound', 'fix': 'MFC 압력 채널 객체 바인딩 누락'},
 'E611': {'cause': '선택된 가스가 없습니다. gas_select()를 먼저 호출하세요', 'fix': 'MFC 사용 전에 gas_select 필수 호출'},
 'E612': {'cause': '지원하지 않는 가스 채널', 'fix': 'mfc.gas_select에 허용된 채널만 사용(장비 채널 구성 확인)'},
 'E613': {'cause': 'READ_PRESSURE 응답 없음', 'fix': 'MFC 압력 읽기 통신/케이블/주소 확인'},
 'E614': {'cause': 'READ_FLOW R60 파싱 실패', 'fix': 'MFC 유량 응답 포맷/구분자 확인, 통신 깨짐 여부 점검'},
 'E615': {'cause': 'SP1 설정 확인 실패', 'fix': 'SP1 write 후 readback 불일치 → 통신/장비 상태 점검'},
 'E616': {'cause': 'SP2 설정 확인 실패', 'fix': 'SP2 write 후 readback 불일치 → 통신/장비 상태 점검'},
 'E617': {'cause': 'SP4 설정 확인 실패', 'fix': 'SP4 write 후 readback 불일치 → 통신/장비 상태 점검'},
 'E618': {'cause': 'SP1 상태 확인 실패', 'fix': 'SP1 ON/OFF 반영 안됨 → 릴레이/장비 상태/통신 점검'},
 'E619': {'cause': 'SP2 상태 확인 실패', 'fix': 'SP2 ON/OFF 반영 안됨 → 릴레이/장비 상태/통신 점검'},
 'E620': {'cause': 'SP3 상태 확인 실패', 'fix': 'SP3 ON/OFF 반영 안됨 → 릴레이/장비 상태/통신 점검'},
 'E621': {'cause': 'SP4 상태 확인 실패', 'fix': 'SP4 ON/OFF 반영 안됨 → 릴레이/장비 상태/통신 점검'},
 'E622': {'cause': 'FLOW_ON R69 읽기 실패 / 적용 불일치', 'fix': 'Flow on/off readback 확인 실패 → 통신/장비 상태 점검'},
 'E623': {'cause': "KeyError '{x}' is required for {cmd}", 'fix': 'MFC_CMD args에 필수 키 누락 → 레시피/호출부 수정'},
 'E624': {'cause': 'invalid {k} for {cmd}', 'fix': '값 범위/타입 오류 → 숫자/단위/허용범위 확인'},
 'E701': {'cause': 'DC_POWER target_failed (저전력 연속 발생)', 'fix': '타깃/방전 상태/아크/가스/압력 확인, setpoint/허용오차 재설정'},
 'E702': {'cause': 'DC_POWER low_current (저전류 연속 발생)', 'fix': '플라즈마 꺼짐/아크/케이블/타깃 접촉 문제 점검, 인터락/냉각수 확인'},
 'E703': {'cause': 'DC_PULSE CONNECT 연결 준비 실패', 'fix': 'DC Pulse 장비 통신(TCP/Serial) 설정 확인, 장비 전원/포트 점검'},
 'E704': {'cause': 'DC_PULSE AUTO_STOP low_current (저전류 연속)', 'fix': '방전 불안정/매칭/가스/압력 확인, DCP_I_LOW_THRESH_A 및 카운트 재검토'},
 'E705': {'cause': 'DC_PULSE AUTO_STOP setpoint deviation(세트포인트 이탈 연속)', 'fix': '목표 파워 도달 불가/부하 변동 → 램프업/허용오차(P_SET_TOL) 조정, 공정조건 점검'},
 'E706': {'cause': 'RF_POWER reflected 안정화 타임아웃(Ref.P 과다 지속)', 'fix': '매칭/부하/타깃 상태 점검, Ref 임계/시간 설정 재검토'},
 'E707': {'cause': 'RF_POWER forward power too low(For.P 미도달 연속)', 'fix': 'RF 출력/매칭/부하/가스/압력 점검, 목표 For 설정 재검토'},
 'E708': {'cause': 'RF_PULSE FORP_MONITOR (For.P 목표 미도달)', 'fix': 'RF 출력/매칭/부하 점검, 주파수/듀티/목표 파워 조정'},
 'E709': {'cause': 'RF_PULSE REFP_MONITOR (Ref.P 임계 초과)', 'fix': '매칭/부하 이상, 아크 가능 → 즉시 조건 점검 후 재시도, Ref 제한/정지 조건 확인'},
 'E710': {'cause': 'DC_PULSE pack_write width invalid(0/1/2만 허용)', 'fix': '프레임 패킹 호출부의 width 인자를 0/1/2로 고정'},
 'E711': {'cause': 'PlasmaCleaningController 게이트밸브 인터락 FALSE', 'fix': 'PLC G_V 인터락 조건 해소 후 재시도'},
 'E712': {'cause': 'PlasmaCleaningController GV OPEN_LAMP TRUE 아님(오픈 실패)', 'fix': '밸브 구동/센서/PLC 주소 확인'},
 'E713': {'cause': 'PlasmaCleaningController IG API 바인딩되지 않음', 'fix': '컨트롤러에 ig_wait_for_base_torr 콜백 주입 확인'},
 'E714': {'cause': 'PlasmaCleaningController Base pressure not reached', 'fix': '누설/펌프/밸브/게이트 상태 점검, 기준 압력/시간 조정'},
 'E801': {'cause': 'OES 초기화 실패', 'fix': 'OES 장치 연결/드라이버/포트 확인, 장치가 점유 중인지 확인'},
 'E802': {'cause': 'OES 장치/픽셀 수 유효하지 않음', 'fix': 'OES 설정(픽셀 범위/채널) 확인, 장치 스펙과 코드 설정 일치'},
 'E803': {'cause': 'RGA 어댑터 없음', 'fix': 'RGA 모듈/드라이버/패키지(srsinst 등) 설치 또는 RGA 기능 비활성'},
 'E804': {'cause': 'TSP 연결되지 않음', 'fix': 'TSP 장비 전원/포트/케이블 확인, connect 시퀀스 확인'},
 'E805': {'cause': 'TSP 빈 응답 / STX 아님 / CRC 불일치', 'fix': '통신 품질(노이즈)/baudrate/프레이밍/케이블 확인, retry/timeout 조정'},
 'E806': {'cause': 'TSP NACK', 'fix': '장비가 명령 거부(상태/권한/모드) → 장비 상태 확인 후 재시도'},
 'E807': {'cause': 'TSP 예상치 못한 응답', 'fix': '프로토콜/펌웨어 차이 가능 → 응답 파서/명령 정의 확인'},
 'E808': {'cause': 'TSP 상태 확인 시간초과', 'fix': '목표 상태 도달 불가 → 장비 상태/조건 점검, timeout 상향'},
 'E901': {'cause': 'plc_remote 로그 저장 실패(__LOGGING_EXCEPTION__)', 'fix': '파일 권한/경로/동시열기(엑셀로 열어 잠김)/디스크 공간 확인, 예외 로그 확인'},
 'E902': {'cause': '로그 폴더 생성 실패/권한 없음', 'fix': '실행 폴더 기준 상대경로인지 확인, Program Files 아래 실행이면 권한 문제 → 사용자 쓰기 가능한 경로로 변경'},
 'E903': {'cause': 'UI/parent not ready (팝업 표시 실패)', 'fix': '백그라운드 스레드/이벤트루프 타이밍 문제 → UI 준비 후 호출, 실패 시 파일로그로 대체'},
 'E904': {'cause': 'parent widget not found (팝업 표시 실패)', 'fix': 'parent 위젯 참조를 runtime에 주입하거나, 안전하게 None이면 팝업 생략'},
 'E905': {'cause': '미처리 예외(Unknown exception)', 'fix': '모든 handler/runtime 경계에서 Exception을 AppError(E999)로 변환해 client/chat/log에 남기도록 정리'},
 'E906': {'cause': 'polling task exited(장비 폴링 태스크 종료)', 'fix': '장비 통신 끊김/예외 → 자동 재시작/재연결 로직 추가 권장'},
 'E907': {'cause': 'CSV 파일 open 실패(잠김/권한)', 'fix': '엑셀로 열린 상태에서 append가 실패할 수 있음 → “복사본 로그” 또는 “파일 잠김 시 재시도/롤링 파일” 적용 권장'},
 'E908': {'cause': '디스크 full/쓰기 실패', 'fix': '저장 경로 공간 확보, 로그 롤링/보관 기간 정책 적용'},
 'E909': {'cause': '네트워크/공유드라이브 불안정(NAS 제외하더라도 경로가 UNC면 영향)', 'fix': '로컬 임시 로그→후속 동기화(스풀링) 구조 권장'},
 'E999': {'cause': 'Internal error (정의되지 않은 예외)', 'fix': 'traceback을 server 로그/파일로그에 저장하고, client에는 E999로 통일 반환(상세는 detail로)'}}

