from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Mapping


# =========================
# 공통 상수
# =========================

ACTION_RETRY = "RETRY"
ACTION_STOP = "STOP"
ACTION_IGNORE = "IGNORE"
ACTION_RETRY_LATER = "RETRY_LATER"   # ✅ 잠시 후 재시도 (쿨다운/BUSY 상태)

SEV_WARN = "WARN"
SEV_ERROR = "ERROR"
SEV_FATAL = "FATAL"


# =========================
# 에러 정의 모델
# =========================

@dataclass(frozen=True)
class ErrorDefinition:
    code: str
    title: str
    category: str
    client_action: str
    severity: str
    cause: str
    fix: str
    is_fallback: bool = False

    def to_dict(self) -> dict:
        return {
            "code": self.code,
            "title": self.title,
            "category": self.category,
            "client_action": self.client_action,
            "severity": self.severity,
            "cause": self.cause,
            "fix": self.fix,
            "is_fallback": self.is_fallback,
        }

    def to_legacy_dict(self) -> dict:
        """
        기존 error_codes_default.py 호환용.
        """
        return {
            "cause": self.cause,
            "fix": self.fix,
        }


# =========================
# 에러 코드 마스터 표
# =========================

ERROR_REGISTRY: Dict[str, ErrorDefinition] = {
    # -----------------------------------------------------------------
    # E1xx : HOST / PROTOCOL / TRANSPORT
    # -----------------------------------------------------------------
    "E101": ErrorDefinition(
        code="E101",
        title="요청 수신 중 연결 종료",
        category="TRANSPORT",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="요청 수신 중 EOF가 발생했습니다. 클라이언트가 전송 도중 연결을 종료했습니다.",
        fix="클라이언트의 소켓 종료 시점, 네트워크 안정성, 요청 전송 흐름을 확인하십시오.",
    ),
    "E102": ErrorDefinition(
        code="E102",
        title="지원하지 않는 프로토콜 버전",
        category="TRANSPORT",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="서버가 지원하지 않는 프로토콜 버전으로 요청이 들어왔습니다.",
        fix="클라이언트와 서버의 프로토콜 버전을 일치시키십시오.",
    ),
    "E103": ErrorDefinition(
        code="E103",
        title="잘못된 헤더",
        category="TRANSPORT",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="요청 헤더 형식 또는 길이가 올바르지 않습니다.",
        fix="패킷 헤더 생성 로직과 길이 계산 로직을 점검하십시오.",
    ),
    "E104": ErrorDefinition(
        code="E104",
        title="잘못된 JSON 본문",
        category="TRANSPORT",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="요청 본문 JSON 디코딩에 실패했습니다.",
        fix="클라이언트가 전송한 JSON 형식과 인코딩을 확인하십시오.",
    ),
    "E105": ErrorDefinition(
        code="E105",
        title="명령 누락",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="요청 본문에 command 필드가 없습니다.",
        fix="클라이언트가 command를 포함하도록 수정하십시오.",
    ),
    "E106": ErrorDefinition(
        code="E106",
        title="알 수 없는 명령",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="등록되지 않은 command가 요청되었습니다.",
        fix="클라이언트 명령명을 서버 라우터 등록값과 일치시키십시오.",
    ),
    "E107": ErrorDefinition(
        code="E107",
        title="응답 직렬화 실패",
        category="TRANSPORT",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="응답 객체를 JSON으로 직렬화하는 중 실패했습니다.",
        fix="응답 payload 안에 직렬화 불가능한 객체가 포함되었는지 확인하십시오.",
    ),
    "E108": ErrorDefinition(
        code="E108",
        title="요청 크기 초과",
        category="TRANSPORT",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="허용된 크기를 초과한 요청이 들어왔습니다.",
        fix="클라이언트 요청 크기를 줄이거나 서버의 제한 정책을 조정하십시오.",
    ),
    "E109": ErrorDefinition(
        code="E109",
        title="응답 전송 중 연결 종료",
        category="TRANSPORT",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="응답 전송 중 broken pipe 또는 connection reset이 발생했습니다.",
        fix="클라이언트와 서버 간 연결 안정성을 확인한 뒤 재시도하십시오.",
    ),
    "E110": ErrorDefinition(
        code="E110",
        title="핸들러 내부 예외",
        category="INTERNAL",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="핸들러 내부에서 예외가 발생했지만, 명시적인 에러코드로 정규화되지 않았습니다.",
        fix="해당 핸들러 내부 예외를 AppError로 명시적으로 변환하십시오.",
        is_fallback=True,
    ),
    "E111": ErrorDefinition(
        code="E111",
        title="핸들러 반환 형식 오류",
        category="INTERNAL",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="핸들러가 dict가 아닌 응답을 반환했습니다.",
        fix="모든 핸들러가 dict 형태의 응답을 반환하도록 수정하십시오.",
    ),
    "E112": ErrorDefinition(
        code="E112",
        title="응답 패킷 구성 실패",
        category="INTERNAL",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="응답 패킷 생성 또는 pack 과정에서 실패했습니다.",
        fix="응답 포맷 생성 로직과 protocol pack 로직을 확인하십시오.",
    ),

    # -----------------------------------------------------------------
    # E2xx : REQUEST / RECIPE / VALIDATION / STATE
    # -----------------------------------------------------------------
    "E201": ErrorDefinition(
        code="E201",
        title="챔버 값 오류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="허용되지 않은 챔버 번호가 전달되었습니다.",
        fix="ch 값은 1 또는 2만 사용하십시오.",
    ),
    "E202": ErrorDefinition(
        code="E202",
        title="레시피 누락",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="레시피 경로 또는 레시피 데이터가 비어 있습니다.",
        fix="레시피 값이 비어 있지 않은지 확인하십시오.",
    ),
    "E203": ErrorDefinition(
        code="E203",
        title="챔버 런타임 미준비",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="챔버 런타임이 아직 준비되지 않았습니다.",
        fix="런타임 초기화 완료 후 다시 시도하십시오.",
    ),
    "E204": ErrorDefinition(
        code="E204",
        title="플라즈마 클리닝 런타임 미준비",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="플라즈마 클리닝 런타임이 아직 준비되지 않았습니다.",
        fix="플라즈마 클리닝 런타임 초기화 완료 후 다시 시도하십시오.",
    ),
    "E205": ErrorDefinition(
        code="E205",
        title="공정 실행 중",
        category="STATE",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="이미 다른 공정이 실행 중이어서 현재 명령을 처리할 수 없습니다.",
        fix="현재 공정 종료 후 다시 시도하십시오.",
    ),
    "E206": ErrorDefinition(
        code="E206",
        title="중복 시작 요청",
        category="STATE",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="다른 시작 요청이 이미 처리 중입니다.",
        fix="기존 시작 요청 처리 완료 후 다시 시도하십시오.",
    ),
    "E207": ErrorDefinition(
        code="E207",
        title="CSV 파일 없음",
        category="RECIPE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="지정한 CSV 파일이 존재하지 않습니다.",
        fix="레시피 파일 경로와 파일 존재 여부를 확인하십시오.",
    ),
    "E208": ErrorDefinition(
        code="E208",
        title="CSV 데이터 없음",
        category="RECIPE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="CSV 파일에 데이터 행이 없거나 공정 데이터가 비어 있습니다.",
        fix="CSV 헤더와 데이터 행을 확인하십시오.",
    ),
    "E209": ErrorDefinition(
        code="E209",
        title="지원하지 않는 레시피 형식",
        category="RECIPE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="현재 지원하지 않는 레시피 형식입니다.",
        fix="지원되는 CSV 형식으로 레시피를 준비하십시오.",
    ),
    "E210": ErrorDefinition(
        code="E210",
        title="사전점검 시간 초과",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="preflight 또는 시작 전 점검 과정이 제한 시간 내 완료되지 않았습니다.",
        fix="장비 준비 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E211": ErrorDefinition(
        code="E211",
        title="시퀀스 검증 실패",
        category="RECIPE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="공정 시퀀스 유효성 검사에 실패했습니다.",
        fix="레시피 순서와 액션 구성 규칙을 확인하십시오.",
    ),
    "E212": ErrorDefinition(
        code="E212",
        title="알 수 없는 런타임 종류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="지원하지 않는 runtime kind가 전달되었습니다.",
        fix="런타임 종류 문자열을 서버가 허용하는 값으로 맞추십시오.",
    ),
    "E213": ErrorDefinition(
        code="E213",
        title="알 수 없는 액션",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="지원하지 않는 공정 액션이 포함되어 있습니다.",
        fix="레시피 액션명을 서버가 지원하는 값으로 수정하십시오.",
    ),
    "E214": ErrorDefinition(
        code="E214",
        title="DELAY 시간 누락",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="DELAY 액션에 duration 값이 없습니다.",
        fix="DELAY 액션에 duration 값을 추가하십시오.",
    ),
    "E215": ErrorDefinition(
        code="E215",
        title="병렬 블록 내 DELAY 사용 불가",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="병렬 블록 안에 DELAY 액션이 포함되었습니다.",
        fix="DELAY는 병렬 블록이 아닌 순차 블록에서만 사용하십시오.",
    ),
    "E216": ErrorDefinition(
        code="E216",
        title="PLC 명령 파라미터 오류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="PLC_CMD 파라미터 형식이 올바르지 않습니다.",
        fix="PLC_CMD 파라미터 구조를 확인하십시오.",
    ),
    "E217": ErrorDefinition(
        code="E217",
        title="MFC 명령 파라미터 오류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="MFC_CMD 파라미터 형식이 올바르지 않습니다.",
        fix="MFC_CMD 파라미터 구조를 확인하십시오.",
    ),
    "E218": ErrorDefinition(
        code="E218",
        title="OES 실행 파라미터 오류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="OES_RUN 파라미터 형식이 올바르지 않습니다.",
        fix="OES_RUN 파라미터 구조를 확인하십시오.",
    ),
    "E219": ErrorDefinition(
        code="E219",
        title="DC Pulse 시작 값 누락",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="DC_PULSE_START에 필요한 value가 없습니다.",
        fix="DC_PULSE_START에 value를 포함하십시오.",
    ),
    "E220": ErrorDefinition(
        code="E220",
        title="RF Pulse 시작 값 누락",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="RF_PULSE_START에 필요한 value가 없습니다.",
        fix="RF_PULSE_START에 value를 포함하십시오.",
    ),
    "E221": ErrorDefinition(
        code="E221",
        title="DC Pulse 시작 파라미터 오류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="DC_PULSE_START 파라미터 형식이 올바르지 않습니다.",
        fix="DC_PULSE_START 파라미터 구조를 확인하십시오.",
    ),
    "E222": ErrorDefinition(
        code="E222",
        title="RF Pulse 시작 파라미터 오류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="RF_PULSE_START 파라미터 형식이 올바르지 않습니다.",
        fix="RF_PULSE_START 파라미터 구조를 확인하십시오.",
    ),
    "E223": ErrorDefinition(
        code="E223",
        title="TSP 목표 압력 누락",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="TSP 목표 압력 입력값이 없습니다.",
        fix="TSP 목표 압력 값을 입력하십시오.",
    ),
    "E224": ErrorDefinition(
        code="E224",
        title="TSP 반복 횟수 누락",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="TSP 반복 횟수 입력값이 없습니다.",
        fix="TSP 반복 횟수를 입력하십시오.",
    ),
    "E225": ErrorDefinition(
        code="E225",
        title="TSP 반복 횟수 오류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="TSP 반복 횟수가 1보다 작습니다.",
        fix="TSP 반복 횟수를 1 이상으로 설정하십시오.",
    ),
    "E226": ErrorDefinition(
        code="E226",
        title="레시피 폴더 값 오류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="GET_RECIPE 요청의 folder 값이 허용 범위를 벗어났습니다.",
        fix="folder 값은 서버가 허용하는 폴더명만 사용하십시오.",
    ),
    "E227": ErrorDefinition(
        code="E227",
        title="레시피 조회 시간 초과",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="GET_RECIPE 처리 중 제한 시간을 초과했습니다.",
        fix="폴더 접근 상태와 저장소 응답 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E228": ErrorDefinition(
        code="E228",
        title="상태 API 요청 형식 오류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="state API 또는 recovery 요청의 payload 형식이 올바르지 않습니다.",
        fix="상태 API payload 구조를 확인하십시오.",
    ),
    "E229": ErrorDefinition(
        code="E229",
        title="상태 API 필수값 누락",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="상태 API 요청에서 필수 필드가 누락되었습니다.",
        fix="필수 필드를 모두 포함하도록 클라이언트를 수정하십시오.",
    ),

    # -----------------------------------------------------------------
    # E3xx : SAFETY / GATE / VACUUM / PIN / CHUCK
    # -----------------------------------------------------------------
    "E301": ErrorDefinition(
        code="E301",
        title="게이트 닫힘 미확인",
        category="SAFETY_GATE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="게이트가 닫힌 상태가 아니므로 공정을 시작할 수 없습니다.",
        fix="게이트 닫힘 상태와 램프를 확인하십시오.",
    ),
    "E302": ErrorDefinition(
        code="E302",
        title="게이트 인터락 불일치",
        category="SAFETY_GATE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="게이트 OPEN 조건의 인터락이 FALSE입니다.",
        fix="PLC 게이트 인터락 조건, 센서, 배선, 기구 상태를 확인하십시오.",
    ),
    "E303": ErrorDefinition(
        code="E303",
        title="반대쪽 게이트 닫힘 미확인",
        category="SAFETY_GATE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="다른 챔버의 게이트가 닫혀 있는 것이 확인되지 않았습니다.",
        fix="반대편 게이트 close 램프와 인터락을 확인하십시오.",
    ),
    "E304": ErrorDefinition(
        code="E304",
        title="게이트 열림 램프 시간 초과",
        category="SAFETY_GATE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="게이트 열림 명령 후 OPEN_LAMP가 제한 시간 내 켜지지 않았습니다.",
        fix="게이트 구동부, 센서, PLC 출력, 공압 상태를 확인하십시오.",
    ),
    "E305": ErrorDefinition(
        code="E305",
        title="게이트 닫힘 램프 시간 초과",
        category="SAFETY_GATE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="게이트 닫힘 명령 후 CLOSE_LAMP가 제한 시간 내 켜지지 않았습니다.",
        fix="게이트 구동부, 센서, PLC 출력, 공압 상태를 확인하십시오.",
    ),
    "E306": ErrorDefinition(
        code="E306",
        title="게이트 센서 모순",
        category="SAFETY_GATE",
        client_action=ACTION_STOP,
        severity=SEV_FATAL,
        cause="게이트 OPEN/CLOSE 센서 상태가 논리적으로 모순됩니다.",
        fix="센서 배선, PLC 주소맵, 기구부 위치 검출 상태를 점검하십시오.",
    ),
    "E307": ErrorDefinition(
        code="E307",
        title="진공 시작 전 게이트 닫힘 미확인",
        category="SAFETY_VACUUM",
        client_action=ACTION_STOP,
        severity=SEV_FATAL,
        cause="게이트가 닫힌 상태가 아닌데 진공 ON을 시도했습니다.",
        fix="게이트 close 램프와 인터락을 먼저 확인하십시오.",
    ),
    "E308": ErrorDefinition(
        code="E308",
        title="진공 해제 전 게이트 닫힘 미확인",
        category="SAFETY_VACUUM",
        client_action=ACTION_STOP,
        severity=SEV_FATAL,
        cause="게이트 닫힘 확인 없이 진공 해제 또는 대기압 전환을 시도했습니다.",
        fix="게이트 close 램프를 먼저 확인한 뒤 진공 해제 동작을 수행하십시오.",
    ),
    "E309": ErrorDefinition(
        code="E309",
        title="러핑펌프 오프 타이머 진행 중",
        category="SAFETY_VACUUM",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="러핑펌프 오프 타이머가 아직 진행 중입니다.",
        fix="타이머 만료 후 다시 시도하십시오.",
    ),
    "E310": ErrorDefinition(
        code="E310",
        title="러핑 밸브 인터락 불일치",
        category="SAFETY_VACUUM",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="러핑 밸브 인터락이 FALSE입니다.",
        fix="L_R_V 관련 인터락 조건과 밸브 상태를 점검하십시오.",
    ),
    "E311": ErrorDefinition(
        code="E311",
        title="벤트 인터락 불일치",
        category="SAFETY_VACUUM",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="벤트 인터락이 FALSE입니다.",
        fix="벤트 동작 조건과 관련 밸브, 센서 상태를 확인하십시오.",
    ),
    "E312": ErrorDefinition(
        code="E312",
        title="진공 형성 시간 초과",
        category="SAFETY_VACUUM",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="제한 시간 내 진공 ready 상태에 도달하지 못했습니다.",
        fix="누설, 밸브 상태, 펌프 상태, 진공 게이지 상태를 확인하십시오.",
    ),
    "E313": ErrorDefinition(
        code="E313",
        title="대기압 복귀 시간 초과",
        category="SAFETY_VACUUM",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="제한 시간 내 대기압 상태에 도달하지 못했습니다.",
        fix="벤트 밸브, 게이지, 배관 상태를 확인하십시오.",
    ),
    "E314": ErrorDefinition(
        code="E314",
        title="핀 상승 인터락 불일치",
        category="SAFETY_PIN_CHUCK",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="핀 상승 인터락이 FALSE입니다.",
        fix="핀 상승 조건과 관련 센서, 인터락을 확인하십시오.",
    ),
    "E315": ErrorDefinition(
        code="E315",
        title="핀 하강 인터락 불일치",
        category="SAFETY_PIN_CHUCK",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="핀 하강 인터락이 FALSE입니다.",
        fix="핀 하강 조건과 관련 센서, 인터락을 확인하십시오.",
    ),
    "E316": ErrorDefinition(
        code="E316",
        title="핀 상승 램프 시간 초과",
        category="SAFETY_PIN_CHUCK",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="핀 상승 명령 후 UP_LAMP가 제한 시간 내 켜지지 않았습니다.",
        fix="핀 구동부, 공압, 센서, PLC 출력을 점검하십시오.",
    ),
    "E317": ErrorDefinition(
        code="E317",
        title="핀 하강 램프 시간 초과",
        category="SAFETY_PIN_CHUCK",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="핀 하강 명령 후 DOWN_LAMP가 제한 시간 내 켜지지 않았습니다.",
        fix="핀 구동부, 공압, 센서, PLC 출력을 점검하십시오.",
    ),
    "E318": ErrorDefinition(
        code="E318",
        title="척 위치 이동 시간 초과",
        category="SAFETY_PIN_CHUCK",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="척이 목표 위치로 제한 시간 내 이동하지 못했습니다.",
        fix="척 구동부, 위치센서, PLC 출력 상태를 확인하십시오.",
    ),
    "E319": ErrorDefinition(
        code="E319",
        title="게이트 열린 상태에서 진공 출력 감지",
        category="SAFETY_VACUUM",
        client_action=ACTION_STOP,
        severity=SEV_FATAL,
        cause="게이트가 열린 상태인데 진공 관련 출력이 활성화되었습니다.",
        fix="PLC 시퀀스와 인터락 로직을 즉시 점검하십시오.",
    ),
    "E320": ErrorDefinition(
        code="E320",
        title="게이트 상태 조회 챔버 오류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="게이트 상태 조회에 잘못된 챔버 번호가 사용되었습니다.",
        fix="게이트 상태 조회 시 ch 값은 1 또는 2만 사용하십시오.",
    ),
    "E321": ErrorDefinition(
        code="E321",
        title="로드락 상태상 게이트 열기 불가",
        category="SAFETY_GATE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="현재 로드락 상태에서는 게이트를 열 수 없습니다.",
        fix="로드락 진공 상태, 벤트 상태, 인터락 조건을 확인하십시오.",
    ),
    "E322": ErrorDefinition(
        code="E322",
        title="진공 상태 신호 모순",
        category="SAFETY_VACUUM",
        client_action=ACTION_STOP,
        severity=SEV_FATAL,
        cause="VAC_READY와 VAC_NOT_READY 신호가 논리적으로 모순됩니다.",
        fix="PLC 상태비트 정의와 진공 상태 신호를 점검하십시오.",
    ),
    "E323": ErrorDefinition(
        code="E323",
        title="아날로그 입력 모듈 오류",
        category="PLC_COMM",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="아날로그 입력 모듈 에러 비트가 감지되었습니다.",
        fix="PLC 아날로그 입력 모듈 상태, 배선, 모듈 자체를 확인하십시오.",
    ),
    "E324": ErrorDefinition(
        code="E324",
        title="아날로그 출력 모듈 오류",
        category="PLC_COMM",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="아날로그 출력 모듈 채널 에러 비트가 감지되었습니다.",
        fix="PLC 아날로그 출력 모듈 상태, 배선, 채널 상태를 확인하십시오.",
    ),
    "E325": ErrorDefinition(
        code="E325",
        title="아날로그 입력 모듈 미준비",
        category="PLC_COMM",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="아날로그 입력 모듈 ready 비트가 FALSE입니다.",
        fix="모듈 초기화 상태와 ready 신호를 확인하십시오.",
    ),
    "E326": ErrorDefinition(
        code="E326",
        title="아날로그 출력 모듈 미준비",
        category="PLC_COMM",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="아날로그 출력 모듈 ready 비트가 FALSE입니다.",
        fix="모듈 초기화 상태와 ready 신호를 확인하십시오.",
    ),
    "E330": ErrorDefinition(
        code="E330",
        title="메인 셔터 인터락 불일치",
        category="SAFETY_GATE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="메인 셔터를 열기 위한 인터락 조건이 충족되지 않았습니다.",
        fix="CH2 메인 셔터 인터락 조건, 램프, 관련 PLC 신호를 확인하십시오.",
    ),
    "E331": ErrorDefinition(
        code="E331",
        title="메인 셔터 닫힘 실패",
        category="SAFETY_GATE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="CH2 게이트 close 후 메인 셔터 닫힘이 완료되지 않았습니다.",
        fix="메인 셔터 close 신호와 램프, 기구부 상태를 확인하십시오.",
    ),

    # -----------------------------------------------------------------
    # E4xx : PLC COMM / PLC MAP / PLC API
    # -----------------------------------------------------------------
    "E401": ErrorDefinition(
        code="E401",
        title="PLC 연결 실패",
        category="PLC_COMM",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="PLC(Modbus) 연결에 실패했습니다.",
        fix="PLC 전원, IP, 포트, 네트워크 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E402": ErrorDefinition(
        code="E402",
        title="PLC 응답 없음",
        category="PLC_COMM",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="PLC가 요청에 응답하지 않았습니다.",
        fix="통신 상태를 확인하고 상태 조회 후 다시 시도하십시오.",
    ),
    "E403": ErrorDefinition(
        code="E403",
        title="PLC 예외 응답",
        category="PLC_COMM",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="PLC가 예외 응답을 반환했습니다.",
        fix="요청 주소, 데이터 길이, PLC 상태를 점검하십시오.",
    ),
    "E404": ErrorDefinition(
        code="E404",
        title="알 수 없는 PLC 주소명",
        category="PLC_MAP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="정의되지 않은 PLC 이름 또는 주소명이 사용되었습니다.",
        fix="PLC 주소 맵 정의와 실제 참조 이름을 일치시키십시오.",
    ),
    "E405": ErrorDefinition(
        code="E405",
        title="PLC 코일 맵 키 누락",
        category="PLC_MAP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="PLC_COIL_MAP에서 필요한 키를 찾지 못했습니다.",
        fix="PLC_COIL_MAP 정의를 점검하십시오.",
    ),
    "E406": ErrorDefinition(
        code="E406",
        title="PLC 레지스터 맵 키 누락",
        category="PLC_MAP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="PLC_REG_MAP에서 필요한 키를 찾지 못했습니다.",
        fix="PLC_REG_MAP 정의를 점검하십시오.",
    ),
    "E407": ErrorDefinition(
        code="E407",
        title="PLC 이름 누락",
        category="PLC_MAP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="PLC 접근 시 필수 name 인자가 없습니다.",
        fix="PLC 접근 함수 호출부에 name을 정확히 전달하십시오.",
    ),
    "E408": ErrorDefinition(
        code="E408",
        title="지원하지 않는 PLC 논리키",
        category="PLC_MAP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="지원하지 않는 PLC 논리키가 사용되었습니다.",
        fix="허용된 PLC 키만 사용하도록 코드를 수정하십시오.",
    ),
    "E409": ErrorDefinition(
        code="E409",
        title="잘못된 가스 종류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="허용되지 않은 가스 enum 또는 이름이 전달되었습니다.",
        fix="가스 종류는 서버가 허용하는 값만 사용하십시오.",
    ),
    "E410": ErrorDefinition(
        code="E410",
        title="챔버에 없는 가스 요청",
        category="PLC_MAP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="해당 챔버에 정의되지 않은 가스 채널이 요청되었습니다.",
        fix="챔버별 가스 채널 정의를 확인하십시오.",
    ),
    "E411": ErrorDefinition(
        code="E411",
        title="필수 PLC 키 누락",
        category="PLC_MAP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="필수 PLC 키(센서, 램프, 로딩 신호 등)가 정의되어 있지 않습니다.",
        fix="주소맵과 키 정의를 보완하십시오.",
    ),
    "E412": ErrorDefinition(
        code="E412",
        title="PLC 비트 읽기 실패",
        category="PLC_COMM",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="PLC 비트 읽기 과정에서 예외가 발생했습니다.",
        fix="PLC 통신 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E413": ErrorDefinition(
        code="E413",
        title="특정 비트 조회 시간 초과",
        category="PLC_COMM",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="특정 PLC 비트를 제한 시간 내 읽지 못했습니다.",
        fix="일시적인 통신 지연 여부를 확인하고 다시 시도하십시오.",
    ),
    "E414": ErrorDefinition(
        code="E414",
        title="워치독 일시중지 실패",
        category="PLC_COMM",
        client_action=ACTION_IGNORE,
        severity=SEV_WARN,
        cause="워치독 pause 호출에 실패했습니다.",
        fix="워치독 상태를 로그로 남기고 필요 시 후속 점검하십시오.",
    ),
    "E415": ErrorDefinition(
        code="E415",
        title="워치독 재개 실패",
        category="PLC_COMM",
        client_action=ACTION_IGNORE,
        severity=SEV_WARN,
        cause="워치독 resume 호출에 실패했습니다.",
        fix="워치독 상태를 로그로 남기고 필요 시 후속 점검하십시오.",
    ),
    "E416": ErrorDefinition(
        code="E416",
        title="PLC 쓰기 실패",
        category="PLC_COMM",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="PLC 코일 또는 레지스터 쓰기에 실패했습니다.",
        fix="PLC 통신, 주소, 권한, 대상 장비 상태를 확인하십시오.",
    ),
    "E417": ErrorDefinition(
        code="E417",
        title="PLC 별칭 해석 실패",
        category="PLC_MAP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="논리명에서 실제 PLC 주소로 변환하지 못했습니다.",
        fix="별칭 정의와 주소 맵을 확인하십시오.",
    ),

    # -----------------------------------------------------------------
    # E5xx : RUNTIME / PRECHECK / CONNECT / RECONNECT
    # -----------------------------------------------------------------
    "E501": ErrorDefinition(
        code="E501",
        title="장비 연결 시간 초과",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="장비 연결이 제한 시간 내 완료되지 않았습니다.",
        fix="장비 전원과 통신 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E502": ErrorDefinition(
        code="E502",
        title="장비 연결 실패",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="장비 연결에 실패했습니다.",
        fix="장비 상태를 확인하고 재연결 후 다시 시도하십시오.",
    ),
    "E503": ErrorDefinition(
        code="E503",
        title="장비 상태 대기 시간 초과",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="장비 상태가 기대값으로 바뀌기를 기다리다 시간 초과되었습니다.",
        fix="장비 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E504": ErrorDefinition(
        code="E504",
        title="안정화 목표 없음",
        category="RUNTIME",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="안정화 대상 값이 정의되지 않았습니다.",
        fix="안정화에 필요한 목표값을 설정하십시오.",
    ),
    "E505": ErrorDefinition(
        code="E505",
        title="가스 안정화 시간 초과",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="가스 유량 또는 압력이 안정화되지 못했습니다.",
        fix="MFC 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E506": ErrorDefinition(
        code="E506",
        title="TSP 실행 시간 초과",
        category="RUNTIME",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="TSP 실행이 제한 시간 내 완료되지 않았습니다.",
        fix="TSP 장비 상태와 응답을 확인하십시오.",
    ),
    "E507": ErrorDefinition(
        code="E507",
        title="램프 대기 시간 초과",
        category="RUNTIME",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="목표 램프 상태가 제한 시간 내 도달하지 않았습니다.",
        fix="해당 구동부와 센서 상태를 확인하십시오.",
    ),
    "E508": ErrorDefinition(
        code="E508",
        title="재연결 시간 초과",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="재연결 시도가 제한 시간 내 완료되지 않았습니다.",
        fix="장비 연결 상태를 점검한 뒤 다시 시도하십시오.",
    ),
    "E509": ErrorDefinition(
        code="E509",
        title="재연결 작업 비정상 종료",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="재연결 작업이 예상치 않게 취소되거나 종료되었습니다.",
        fix="재연결 작업 흐름과 취소 조건을 점검하십시오.",
    ),
    "E510": ErrorDefinition(
        code="E510",
        title="재연결 실패",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="재연결 시도가 실패했습니다.",
        fix="장비 상태를 확인하고 다시 시도하십시오.",
    ),
    "E511": ErrorDefinition(
        code="E511",
        title="사전 연결 점검 실패",
        category="RUNTIME",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="공정 시작 전 필수 장비 연결 점검에 실패했습니다.",
        fix="시작 전 필수 장비 연결 상태를 모두 확인하십시오.",
    ),
    "E512": ErrorDefinition(
        code="E512",
        title="시작 가드 시간 초과",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="시작 가드 또는 사전 조건 대기가 제한 시간 내 끝나지 않았습니다.",
        fix="상태가 정리된 후 다시 시도하십시오.",
    ),
    "E513": ErrorDefinition(
        code="E513",
        title="게이트 열린 상태로 시작 차단",
        category="STATE",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="게이트가 열린 상태여서 공정 시작이 차단되었습니다.",
        fix="게이트를 닫고 close 램프를 확인하십시오.",
    ),
    "E514": ErrorDefinition(
        code="E514",
        title="필수 콜백 누락",
        category="RUNTIME",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="필수 콜백 또는 필수 주입 객체가 설정되지 않았습니다.",
        fix="초기화 및 의존성 주입 로직을 점검하십시오.",
    ),
    "E515": ErrorDefinition(
        code="E515",
        title="이전 시작 작업 대기 중",
        category="STATE",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="이전 start 작업이 아직 완료되지 않았습니다.",
        fix="이전 작업이 끝난 뒤 다시 시도하십시오.",
    ),

    # -----------------------------------------------------------------
    # E6xx : IG / MFC / PRESSURE / GAS
    # -----------------------------------------------------------------
    "E601": ErrorDefinition(
        code="E601",
        title="IG 읽기 콜백 미설정",
        category="IG",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="IG pressure read callback이 바인딩되지 않았습니다.",
        fix="IG read callback 주입 로직을 확인하십시오.",
    ),
    "E602": ErrorDefinition(
        code="E602",
        title="IG 객체 미설정",
        category="IG",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="IG 객체가 주입되지 않았습니다.",
        fix="IG 초기화 및 주입 로직을 확인하십시오.",
    ),
    "E603": ErrorDefinition(
        code="E603",
        title="IG API 누락",
        category="IG",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="IG 객체에 필요한 read API가 없습니다.",
        fix="IG 클래스 구현과 사용 API를 확인하십시오.",
    ),
    "E604": ErrorDefinition(
        code="E604",
        title="IG 읽기 API 탐색 실패",
        category="IG",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="main 또는 runtime에서 IG 읽기 API를 찾지 못했습니다.",
        fix="IG 객체 참조 경로와 메서드명을 확인하십시오.",
    ),
    "E605": ErrorDefinition(
        code="E605",
        title="IG 활성화 실패",
        category="IG",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="IG ensure_on 또는 활성화 과정에 실패했습니다.",
        fix="게이지 전원과 통신 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E606": ErrorDefinition(
        code="E606",
        title="IG 응답 시간 초과",
        category="IG",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="IG에서 제한 시간 내 응답이 오지 않았습니다.",
        fix="IG 통신 상태를 확인하고 다시 시도하십시오.",
    ),
    "E607": ErrorDefinition(
        code="E607",
        title="IG 파싱 오류",
        category="IG",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="IG 응답값 파싱에 실패했습니다.",
        fix="IG 응답 형식과 파싱 로직을 확인하십시오.",
    ),
    "E608": ErrorDefinition(
        code="E608",
        title="기저압 미도달",
        category="IG",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="기저압이 목표값 이하로 내려가지 않았습니다.",
        fix="누설, 펌프 상태, 배관 상태, 진공 게이지 값을 점검하십시오.",
    ),
    "E609": ErrorDefinition(
        code="E609",
        title="MFC 가스 객체 미설정",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="mfc_gas 객체가 바인딩되지 않았습니다.",
        fix="MFC gas 객체 주입 로직을 확인하십시오.",
    ),
    "E610": ErrorDefinition(
        code="E610",
        title="MFC 압력 객체 미설정",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="mfc_pressure 객체가 바인딩되지 않았습니다.",
        fix="MFC pressure 객체 주입 로직을 확인하십시오.",
    ),
    "E611": ErrorDefinition(
        code="E611",
        title="가스 선택 누락",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="MFC 동작 전에 가스 선택이 완료되지 않았습니다.",
        fix="gas_select 호출 흐름을 확인하십시오.",
    ),
    "E612": ErrorDefinition(
        code="E612",
        title="지원하지 않는 가스 채널",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="지원하지 않는 가스 채널이 요청되었습니다.",
        fix="허용된 가스 채널만 사용하십시오.",
    ),
    "E613": ErrorDefinition(
        code="E613",
        title="압력 읽기 응답 없음",
        category="MFC",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="MFC pressure read 요청에 응답이 없습니다.",
        fix="MFC 통신 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E614": ErrorDefinition(
        code="E614",
        title="유량 읽기 파싱 실패",
        category="MFC",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="MFC flow read 응답 파싱에 실패했습니다.",
        fix="MFC 응답 형식과 통신 상태를 확인하십시오.",
    ),
    "E615": ErrorDefinition(
        code="E615",
        title="SP1 검증 실패",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="SP1 readback 값이 기대값과 일치하지 않습니다.",
        fix="SP1 설정 및 readback 로직을 확인하십시오.",
    ),
    "E616": ErrorDefinition(
        code="E616",
        title="SP2 검증 실패",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="SP2 readback 값이 기대값과 일치하지 않습니다.",
        fix="SP2 설정 및 readback 로직을 확인하십시오.",
    ),
    "E617": ErrorDefinition(
        code="E617",
        title="SP4 검증 실패",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="SP4 readback 값이 기대값과 일치하지 않습니다.",
        fix="SP4 설정 및 readback 로직을 확인하십시오.",
    ),
    "E618": ErrorDefinition(
        code="E618",
        title="SP1 상태 적용 실패",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="SP1 상태 변경이 반영되지 않았습니다.",
        fix="SP1 on/off 제어 로직과 readback을 확인하십시오.",
    ),
    "E619": ErrorDefinition(
        code="E619",
        title="SP2 상태 적용 실패",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="SP2 상태 변경이 반영되지 않았습니다.",
        fix="SP2 on/off 제어 로직과 readback을 확인하십시오.",
    ),
    "E620": ErrorDefinition(
        code="E620",
        title="SP3 상태 적용 실패",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="SP3 상태 변경이 반영되지 않았습니다.",
        fix="SP3 on/off 제어 로직과 readback을 확인하십시오.",
    ),
    "E621": ErrorDefinition(
        code="E621",
        title="SP4 상태 적용 실패",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="SP4 상태 변경이 반영되지 않았습니다.",
        fix="SP4 on/off 제어 로직과 readback을 확인하십시오.",
    ),
    "E622": ErrorDefinition(
        code="E622",
        title="FLOW_ON 검증 실패",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="FLOW_ON 상태가 기대값과 일치하지 않습니다.",
        fix="유량 ON/OFF 제어와 readback 값을 확인하십시오.",
    ),
    "E623": ErrorDefinition(
        code="E623",
        title="MFC 필수 인자 누락",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="MFC 명령에 필요한 필수 인자가 없습니다.",
        fix="해당 MFC 명령의 필수 인자를 모두 전달하십시오.",
    ),
    "E624": ErrorDefinition(
        code="E624",
        title="MFC 인자 값 오류",
        category="REQUEST",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="MFC 명령 인자 값이 허용 범위를 벗어났습니다.",
        fix="MFC 명령 인자 형식과 범위를 확인하십시오.",
    ),
    "E625": ErrorDefinition(
        code="E625",
        title="가스 상태 불일치",
        category="MFC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="선택된 가스 상태와 실제 MFC 상태가 일치하지 않습니다.",
        fix="가스 선택 로직과 채널 상태를 확인하십시오.",
    ),
    "E626": ErrorDefinition(
        code="E626",
        title="압력 콜백 시간 초과",
        category="IG",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="실행 중 pressure callback 응답이 제한 시간 내 오지 않았습니다.",
        fix="압력 읽기 경로와 통신 상태를 확인한 뒤 다시 시도하십시오.",
    ),

    # -----------------------------------------------------------------
    # E7xx : POWER / PLASMA / PLASMA CLEANING
    # -----------------------------------------------------------------
    "E701": ErrorDefinition(
        code="E701",
        title="DC 목표 도달 실패",
        category="POWER_DC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="DC 파워가 목표 출력에 도달하지 못했습니다.",
        fix="DC 전원장치 상태, 부하 상태, 배선 상태를 점검하십시오.",
    ),
    "E702": ErrorDefinition(
        code="E702",
        title="DC 저전류 감지",
        category="POWER_DC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="DC 전류가 허용치보다 낮아 비정상으로 판단되었습니다.",
        fix="플라즈마 형성 상태, 타깃 상태, 배선 상태를 확인하십시오.",
    ),
    "E703": ErrorDefinition(
        code="E703",
        title="DC Pulse 연결 준비 실패",
        category="POWER_DC",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="DC Pulse 장비 연결 준비가 완료되지 않았습니다.",
        fix="장비 연결 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E704": ErrorDefinition(
        code="E704",
        title="DC Pulse 저전류 자동정지",
        category="POWER_DC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="DC Pulse가 저전류 조건으로 자동 정지되었습니다.",
        fix="전원장치 상태, 플라즈마 상태, 부하 상태를 확인하십시오.",
    ),
    "E705": ErrorDefinition(
        code="E705",
        title="DC Pulse 설정값 편차 과다",
        category="POWER_DC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="DC Pulse 실제 출력이 설정값에서 크게 벗어났습니다.",
        fix="설정값, readback, 장비 상태를 확인하십시오.",
    ),
    "E706": ErrorDefinition(
        code="E706",
        title="RF 반사파 안정화 실패",
        category="POWER_RF",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="RF reflected power가 제한 시간 내 안정화되지 않았습니다.",
        fix="매칭 상태, 반사파 상태, 케이블, 부하 상태를 점검하십시오.",
    ),
    "E707": ErrorDefinition(
        code="E707",
        title="RF 순방향 출력 부족",
        category="POWER_RF",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="RF forward power가 허용치보다 낮습니다.",
        fix="RF 출력, 매칭, 부하 상태를 확인하십시오.",
    ),
    "E708": ErrorDefinition(
        code="E708",
        title="RF Pulse 순방향 감시 실패",
        category="POWER_RF",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="RF Pulse forward power 감시 조건을 만족하지 못했습니다.",
        fix="RF Pulse 장비 설정과 출력 상태를 확인하십시오.",
    ),
    "E709": ErrorDefinition(
        code="E709",
        title="RF Pulse 반사파 한계 초과",
        category="POWER_RF",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="RF Pulse reflected power가 허용 한계를 초과했습니다.",
        fix="매칭 상태와 부하 상태를 즉시 점검하십시오.",
    ),
    "E710": ErrorDefinition(
        code="E710",
        title="DC Pulse 폭 설정 오류",
        category="POWER_DC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="DC Pulse width 값이 허용 범위를 벗어났습니다.",
        fix="width 값은 장비가 허용하는 값만 사용하십시오.",
    ),
    "E711": ErrorDefinition(
        code="E711",
        title="플라즈마 클리닝 게이트 인터락 불일치",
        category="PLASMA_CLEANING",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="플라즈마 클리닝 시작 시 게이트 인터락이 FALSE입니다.",
        fix="게이트 인터락과 로드락 상태를 확인하십시오.",
    ),
    "E712": ErrorDefinition(
        code="E712",
        title="플라즈마 클리닝 게이트 열림 실패",
        category="PLASMA_CLEANING",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="플라즈마 클리닝 시작 시 게이트 OPEN_LAMP가 켜지지 않았습니다.",
        fix="게이트 구동부, 센서, PLC 신호를 확인하십시오.",
    ),
    "E713": ErrorDefinition(
        code="E713",
        title="플라즈마 클리닝 IG 콜백 미설정",
        category="PLASMA_CLEANING",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="플라즈마 클리닝에 필요한 IG callback이 바인딩되지 않았습니다.",
        fix="플라즈마 클리닝 런타임 초기화와 IG 주입을 확인하십시오.",
    ),
    "E714": ErrorDefinition(
        code="E714",
        title="플라즈마 클리닝 기저압 미도달",
        category="PLASMA_CLEANING",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="플라즈마 클리닝 시작 전 기저압에 도달하지 못했습니다.",
        fix="진공 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E715": ErrorDefinition(
        code="E715",
        title="DC Pulse 설정 콜백 미설정",
        category="POWER_DC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="set_dc_pulse_power 콜백이 주입되지 않았습니다.",
        fix="process_controller 초기화 시 DC Pulse 콜백을 연결하십시오.",
    ),
    "E716": ErrorDefinition(
        code="E716",
        title="RF Pulse 설정 콜백 미설정",
        category="POWER_RF",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="set_rf_pulse_power 콜백이 주입되지 않았습니다.",
        fix="process_controller 초기화 시 RF Pulse 콜백을 연결하십시오.",
    ),
    "E717": ErrorDefinition(
        code="E717",
        title="RF Pulse 설정값 누락",
        category="POWER_RF",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="RF Pulse TCP 설정(host/port)이 누락되었습니다.",
        fix="RF Pulse 설정 파일과 초기화 로직을 확인하십시오.",
    ),
    "E718": ErrorDefinition(
        code="E718",
        title="RF Pulse 주소값 오류",
        category="POWER_RF",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="RF Pulse 레지스터 주소가 허용 범위를 벗어났습니다.",
        fix="RF Pulse 주소 계산 로직을 확인하십시오.",
    ),
    "E719": ErrorDefinition(
        code="E719",
        title="플라즈마 클리닝 쿨다운 대기",
        category="PLASMA_CLEANING",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="이전 공정 종료 후 필요한 쿨다운 시간이 지나지 않았습니다.",
        fix="쿨다운 시간이 지난 후 다시 시도하십시오.",
    ),
    "E720": ErrorDefinition(
        code="E720",
        title="파워 설정 후 검증 불일치",
        category="POWER_DC",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="파워 write 이후 readback 값이 기대값과 일치하지 않습니다.",
        fix="전원장치 제어와 readback 검증 로직을 확인하십시오.",
    ),

    # -----------------------------------------------------------------
    # E8xx : OES / RGA / TSP / ETC DEVICE
    # -----------------------------------------------------------------
    "E801": ErrorDefinition(
        code="E801",
        title="OES 초기화 실패",
        category="OES",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="OES 초기화에 실패했습니다.",
        fix="OES 장비 연결과 서비스 초기화 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E802": ErrorDefinition(
        code="E802",
        title="OES 설정값 오류",
        category="OES",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="OES 장치 번호 또는 픽셀 설정값이 올바르지 않습니다.",
        fix="OES 설정 파일과 장치 선택값을 확인하십시오.",
    ),
    "E803": ErrorDefinition(
        code="E803",
        title="RGA 어댑터 없음",
        category="RGA",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="RGA adapter 또는 필수 객체를 찾지 못했습니다.",
        fix="RGA 초기화와 의존성 로직을 확인하십시오.",
    ),
    "E804": ErrorDefinition(
        code="E804",
        title="TSP 연결 안 됨",
        category="TSP",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="TSP 장비가 연결되지 않았습니다.",
        fix="TSP 통신 연결 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E805": ErrorDefinition(
        code="E805",
        title="TSP 프로토콜 응답 오류",
        category="TSP",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="TSP 응답이 비어 있거나 STX/CRC 검증에 실패했습니다.",
        fix="TSP 통신 상태와 응답 프레임을 확인하십시오.",
    ),
    "E806": ErrorDefinition(
        code="E806",
        title="TSP 명령 거부",
        category="TSP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="TSP 장비가 명령을 NACK로 거부했습니다.",
        fix="TSP 명령 형식과 장비 상태를 확인하십시오.",
    ),
    "E807": ErrorDefinition(
        code="E807",
        title="TSP 예상 외 응답",
        category="TSP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="TSP가 예상하지 않은 응답을 반환했습니다.",
        fix="TSP 프로토콜 처리 로직과 장비 상태를 확인하십시오.",
    ),
    "E808": ErrorDefinition(
        code="E808",
        title="TSP 상태 대기 시간 초과",
        category="TSP",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="TSP 상태가 기대값으로 바뀌기를 기다리다 시간 초과되었습니다.",
        fix="TSP 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E809": ErrorDefinition(
        code="E809",
        title="OES 데몬 미준비",
        category="OES",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="OES daemon이 아직 측정 가능한 상태가 아닙니다.",
        fix="OES service 기동 완료 후 다시 시도하십시오.",
    ),
    "E810": ErrorDefinition(
        code="E810",
        title="OES 데몬 전송 실패",
        category="OES",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="OES daemon으로 측정 명령 전송에 실패했습니다.",
        fix="OES service 통신 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E811": ErrorDefinition(
        code="E811",
        title="OES 데몬 측정 실패",
        category="OES",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="OES daemon이 측정 실패를 반환했습니다.",
        fix="OES service 로그와 장비 상태를 점검하십시오.",
    ),
    "E812": ErrorDefinition(
        code="E812",
        title="OES 첫 프레임 수신 실패",
        category="OES",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="OES 첫 측정 프레임 수신에 실패했습니다.",
        fix="장비 준비 상태와 service 초기화 상태를 확인한 뒤 다시 시도하십시오.",
    ),
    "E813": ErrorDefinition(
        code="E813",
        title="OES 장비 준비 안 됨",
        category="OES",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="OES 장비가 측정 준비 상태가 아닙니다.",
        fix="OES 장비 상태와 초기화 절차를 확인하십시오.",
    ),
    "E814": ErrorDefinition(
        code="E814",
        title="RGA 의존성 로드 실패",
        category="RGA",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="RGA 필수 모듈 import 또는 worker 준비에 실패했습니다.",
        fix="RGA 설치 상태와 실행 환경을 확인하십시오.",
    ),
    "E815": ErrorDefinition(
        code="E815",
        title="OES 챔버 인자 오류",
        category="OES",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="OES에 잘못된 챔버 값이 전달되었습니다.",
        fix="OES 호출 시 챔버 값은 1 또는 2만 사용하십시오.",
    ),
    "E816": ErrorDefinition(
        code="E816",
        title="TSP WIN 형식 오류",
        category="TSP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="TSP WIN 값 형식이 장비 규격과 맞지 않습니다.",
        fix="WIN 값 형식을 장비 규격에 맞게 수정하십시오.",
    ),
    "E817": ErrorDefinition(
        code="E817",
        title="TSP 데이터 누락",
        category="TSP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="TSP write 명령에 필요한 DATA가 없습니다.",
        fix="TSP write 명령에 DATA를 포함하십시오.",
    ),
    "E818": ErrorDefinition(
        code="E818",
        title="TSP 프레임 구성 오류",
        category="TSP",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="TSP 명령 프레임 생성값이 올바르지 않습니다.",
        fix="TSP 프레임 생성 로직을 점검하십시오.",
    ),

    # -----------------------------------------------------------------
    # E9xx : LOGGING / UI / INTERNAL / FALLBACK
    # -----------------------------------------------------------------
    "E901": ErrorDefinition(
        code="E901",
        title="로그 저장 실패",
        category="LOGGING",
        client_action=ACTION_IGNORE,
        severity=SEV_WARN,
        cause="로그 파일 저장 또는 append 처리에 실패했습니다.",
        fix="경로, 권한, 파일 잠금, 디스크 상태를 확인하십시오.",
    ),
    "E902": ErrorDefinition(
        code="E902",
        title="로그 폴더 생성 실패",
        category="LOGGING",
        client_action=ACTION_IGNORE,
        severity=SEV_WARN,
        cause="로그 폴더 생성에 실패했습니다.",
        fix="폴더 권한과 경로 유효성을 확인하십시오.",
    ),
    "E903": ErrorDefinition(
        code="E903",
        title="UI 미준비",
        category="UI",
        client_action=ACTION_IGNORE,
        severity=SEV_WARN,
        cause="UI 또는 parent가 아직 준비되지 않았습니다.",
        fix="UI 연결 상태를 점검하되 공정 본체에는 영향이 없는지 확인하십시오.",
    ),
    "E904": ErrorDefinition(
        code="E904",
        title="부모 위젯 없음",
        category="UI",
        client_action=ACTION_IGNORE,
        severity=SEV_WARN,
        cause="필요한 parent widget을 찾지 못했습니다.",
        fix="UI 참조 경로를 확인하십시오.",
    ),
    "E905": ErrorDefinition(
        code="E905",
        title="미처리 예외",
        category="INTERNAL",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="예상하지 못한 예외가 처리되지 않은 채 발생했습니다.",
        fix="traceback을 확인하고 해당 예외를 AppError로 정규화하십시오.",
    ),
    "E906": ErrorDefinition(
        code="E906",
        title="폴링 작업 종료",
        category="RUNTIME",
        client_action=ACTION_RETRY,
        severity=SEV_WARN,
        cause="장비 polling task가 비정상 종료되었습니다.",
        fix="폴링 재시작 또는 장비 재연결 후 다시 시도하십시오.",
    ),
    "E907": ErrorDefinition(
        code="E907",
        title="CSV 파일 열기 실패",
        category="LOGGING",
        client_action=ACTION_IGNORE,
        severity=SEV_WARN,
        cause="CSV 파일 열기 또는 append에 실패했습니다.",
        fix="파일 잠금 여부와 경로 권한을 확인하십시오.",
    ),
    "E908": ErrorDefinition(
        code="E908",
        title="디스크 쓰기 실패",
        category="LOGGING",
        client_action=ACTION_IGNORE,
        severity=SEV_WARN,
        cause="디스크 공간 부족 또는 쓰기 실패가 발생했습니다.",
        fix="디스크 공간과 저장 경로 상태를 확인하십시오.",
    ),
    "E909": ErrorDefinition(
        code="E909",
        title="공유 저장소 불안정",
        category="LOGGING",
        client_action=ACTION_IGNORE,
        severity=SEV_WARN,
        cause="NAS 또는 UNC 경로 접근이 불안정합니다.",
        fix="네트워크 저장소 상태를 확인하고 필요 시 로컬 폴백을 사용하십시오.",
    ),
    "E910": ErrorDefinition(
        code="E910",
        title="런타임 덤프 중복 실행",
        category="INTERNAL",
        client_action=ACTION_IGNORE,
        severity=SEV_WARN,
        cause="runtime dump 작업이 이미 실행 중입니다.",
        fix="중복 덤프 요청을 막고 현재 작업 완료를 기다리십시오.",
    ),
    "E911": ErrorDefinition(
        code="E911",
        title="기본 로그 경로 미설정",
        category="LOGGING",
        client_action=ACTION_IGNORE,
        severity=SEV_WARN,
        cause="기본 로그 저장 경로가 설정되지 않았습니다.",
        fix="로그 초기화 시 primary_path를 설정하십시오.",
    ),
    # ===================================================
    # E7xx: 운영 상태 (BUSY / COOLDOWN / 대기 중)
    # 진짜 에러가 아니라 "잠시 후 재시도" 안내.
    # client_action=RETRY_LATER 로 STOP과 구분됨.
    # ===================================================
    "E700": ErrorDefinition(
        code="E700",
        title="공정 쿨다운 대기 중",
        category="BUSY",
        client_action=ACTION_RETRY_LATER,
        severity=SEV_WARN,
        cause="이전 공정 종료 후 쿨다운 시간(60초)이 필요합니다.",
        fix="안내된 시간 이후 다시 시도하십시오.",
        is_fallback=False,
    ),
    "E999": ErrorDefinition(
        code="E999",
        title="정의되지 않은 내부 예외",
        category="INTERNAL",
        client_action=ACTION_STOP,
        severity=SEV_ERROR,
        cause="명시적으로 분류되지 않은 내부 예외가 발생했습니다.",
        fix="원본 예외를 확인하고 적절한 AppError 코드로 정규화하십시오.",
        is_fallback=True,
    ),
}


# =========================
# 헬퍼 함수
# =========================

def get_error_definition(code: str) -> ErrorDefinition:
    """
    code가 없으면 E999를 반환한다.
    """
    if not code:
        return ERROR_REGISTRY["E999"]
    return ERROR_REGISTRY.get(str(code).strip().upper(), ERROR_REGISTRY["E999"])


def get_error_dict(code: str) -> dict:
    return get_error_definition(code).to_dict()


def get_legacy_error_dict(code: str) -> dict:
    """
    기존 util/error_codes_default.py 호환용.
    """
    return get_error_definition(code).to_legacy_dict()


def is_fallback_error(code: str) -> bool:
    return get_error_definition(code).is_fallback


def get_error_title(code: str) -> str:
    return get_error_definition(code).title


def get_error_category(code: str) -> str:
    return get_error_definition(code).category


def get_client_action(code: str) -> str:
    return get_error_definition(code).client_action


def get_error_severity(code: str) -> str:
    return get_error_definition(code).severity


def get_error_cause(code: str) -> str:
    return get_error_definition(code).cause


def get_error_fix(code: str) -> str:
    return get_error_definition(code).fix


def list_error_codes() -> List[str]:
    return list(ERROR_REGISTRY.keys())


def iter_error_definitions() -> Iterable[ErrorDefinition]:
    return ERROR_REGISTRY.values()


def build_legacy_default_codes() -> Dict[str, dict]:
    """
    기존 DEFAULT_CODES와 같은 형태가 필요할 때 사용.
    """
    return {code: item.to_legacy_dict() for code, item in ERROR_REGISTRY.items()}


def build_registry_snapshot() -> Dict[str, dict]:
    """
    전체 레지스트리를 dict 스냅샷으로 반환.
    """
    return {code: item.to_dict() for code, item in ERROR_REGISTRY.items()}


__all__ = [
    "ACTION_RETRY",
    "ACTION_STOP",
    "ACTION_IGNORE",
    "SEV_WARN",
    "SEV_ERROR",
    "SEV_FATAL",
    "ErrorDefinition",
    "ERROR_REGISTRY",
    "get_error_definition",
    "get_error_dict",
    "get_legacy_error_dict",
    "is_fallback_error",
    "get_error_title",
    "get_error_category",
    "get_client_action",
    "get_error_severity",
    "get_error_cause",
    "get_error_fix",
    "list_error_codes",
    "iter_error_definitions",
    "build_legacy_default_codes",
    "build_registry_snapshot",
]