# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CH1&2tBtzJN.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QButtonGroup, QCheckBox, QLabel,
    QPlainTextEdit, QPushButton, QRadioButton, QSizePolicy,
    QStackedWidget, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1086, 967)
        self.stackedWidget = QStackedWidget(Form)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 10, 1081, 951))
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.PC_rfPower_edit = QPlainTextEdit(self.page_3)
        self.PC_rfPower_edit.setObjectName(u"PC_rfPower_edit")
        self.PC_rfPower_edit.setGeometry(QRect(820, 320, 201, 31))
        self.PC_Hum_edit = QPlainTextEdit(self.page_3)
        self.PC_Hum_edit.setObjectName(u"PC_Hum_edit")
        self.PC_Hum_edit.setGeometry(QRect(890, 470, 61, 31))
        self.PC_Hum_edit.setReadOnly(True)
        self.PC_Temp_edit = QPlainTextEdit(self.page_3)
        self.PC_Temp_edit.setObjectName(u"PC_Temp_edit")
        self.PC_Temp_edit.setGeometry(QRect(820, 470, 61, 31))
        self.PC_Temp_edit.setReadOnly(True)
        self.PC_rfPower_label = QLabel(self.page_3)
        self.PC_rfPower_label.setObjectName(u"PC_rfPower_label")
        self.PC_rfPower_label.setGeometry(QRect(820, 300, 101, 21))
        self.PC_rfPower_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.PC_forP_edit = QPlainTextEdit(self.page_3)
        self.PC_forP_edit.setObjectName(u"PC_forP_edit")
        self.PC_forP_edit.setGeometry(QRect(820, 420, 61, 31))
        self.PC_forP_edit.setReadOnly(True)
        self.plasmaCleaning_label = QLabel(self.page_3)
        self.plasmaCleaning_label.setObjectName(u"plasmaCleaning_label")
        self.plasmaCleaning_label.setGeometry(QRect(800, 40, 241, 91))
        font = QFont()
        font.setPointSize(24)
        self.plasmaCleaning_label.setFont(font)
        self.plasmaCleaning_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.PC_forP_label = QLabel(self.page_3)
        self.PC_forP_label.setObjectName(u"PC_forP_label")
        self.PC_forP_label.setGeometry(QRect(820, 400, 51, 21))
        self.PC_forP_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.preSputter_LeftTime_edit = QPlainTextEdit(self.page_3)
        self.preSputter_LeftTime_edit.setObjectName(u"preSputter_LeftTime_edit")
        self.preSputter_LeftTime_edit.setGeometry(QRect(670, 180, 91, 31))
        self.preSputter_LeftTime_edit.setReadOnly(True)
        self.preSputter_Start_button = QPushButton(self.page_3)
        self.preSputter_Start_button.setObjectName(u"preSputter_Start_button")
        self.preSputter_Start_button.setGeometry(QRect(560, 280, 91, 61))
        self.PC_refP_label = QLabel(self.page_3)
        self.PC_refP_label.setObjectName(u"PC_refP_label")
        self.PC_refP_label.setGeometry(QRect(890, 400, 51, 21))
        self.PC_refP_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.PC_targetPressure_edit = QPlainTextEdit(self.page_3)
        self.PC_targetPressure_edit.setObjectName(u"PC_targetPressure_edit")
        self.PC_targetPressure_edit.setGeometry(QRect(820, 170, 201, 31))
        self.PC_biasV_edit = QPlainTextEdit(self.page_3)
        self.PC_biasV_edit.setObjectName(u"PC_biasV_edit")
        self.PC_biasV_edit.setGeometry(QRect(960, 420, 61, 31))
        self.PC_biasV_edit.setReadOnly(True)
        self.PC_workingPressure_edit = QPlainTextEdit(self.page_3)
        self.PC_workingPressure_edit.setObjectName(u"PC_workingPressure_edit")
        self.PC_workingPressure_edit.setGeometry(QRect(820, 270, 201, 31))
        self.PC_refP_edit = QPlainTextEdit(self.page_3)
        self.PC_refP_edit.setObjectName(u"PC_refP_edit")
        self.PC_refP_edit.setGeometry(QRect(890, 420, 61, 31))
        self.PC_refP_edit.setReadOnly(True)
        self.PC_ProcessTime_label = QLabel(self.page_3)
        self.PC_ProcessTime_label.setObjectName(u"PC_ProcessTime_label")
        self.PC_ProcessTime_label.setGeometry(QRect(820, 350, 141, 21))
        self.PC_ProcessTime_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.PC_Hum_label = QLabel(self.page_3)
        self.PC_Hum_label.setObjectName(u"PC_Hum_label")
        self.PC_Hum_label.setGeometry(QRect(890, 450, 61, 21))
        self.PC_Hum_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.pc_preSputter_label = QLabel(self.page_3)
        self.pc_preSputter_label.setObjectName(u"pc_preSputter_label")
        self.pc_preSputter_label.setGeometry(QRect(570, 60, 181, 51))
        self.pc_preSputter_label.setFont(font)
        self.pc_preSputter_label.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pc_preSputter_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.preSputter_LeftTime_label = QLabel(self.page_3)
        self.preSputter_LeftTime_label.setObjectName(u"preSputter_LeftTime_label")
        self.preSputter_LeftTime_label.setGeometry(QRect(670, 160, 81, 21))
        self.preSputter_LeftTime_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.PC_gasFlow_label = QLabel(self.page_3)
        self.PC_gasFlow_label.setObjectName(u"PC_gasFlow_label")
        self.PC_gasFlow_label.setGeometry(QRect(820, 200, 121, 21))
        self.PC_gasFlow_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.preSputter_SetTime_label = QLabel(self.page_3)
        self.preSputter_SetTime_label.setObjectName(u"preSputter_SetTime_label")
        self.preSputter_SetTime_label.setGeometry(QRect(560, 160, 91, 21))
        self.preSputter_SetTime_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.PC_Temp_label = QLabel(self.page_3)
        self.PC_Temp_label.setObjectName(u"PC_Temp_label")
        self.PC_Temp_label.setGeometry(QRect(820, 450, 61, 21))
        self.PC_Temp_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.preSputter_SetTime_edit = QPlainTextEdit(self.page_3)
        self.preSputter_SetTime_edit.setObjectName(u"preSputter_SetTime_edit")
        self.preSputter_SetTime_edit.setGeometry(QRect(560, 180, 91, 31))
        self.PC_workingPressure_label = QLabel(self.page_3)
        self.PC_workingPressure_label.setObjectName(u"PC_workingPressure_label")
        self.PC_workingPressure_label.setGeometry(QRect(820, 250, 181, 21))
        self.PC_workingPressure_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.PC_gasFlow_edit = QPlainTextEdit(self.page_3)
        self.PC_gasFlow_edit.setObjectName(u"PC_gasFlow_edit")
        self.PC_gasFlow_edit.setGeometry(QRect(820, 220, 201, 31))
        self.PC_targetPressure_label = QLabel(self.page_3)
        self.PC_targetPressure_label.setObjectName(u"PC_targetPressure_label")
        self.PC_targetPressure_label.setGeometry(QRect(820, 150, 151, 21))
        self.PC_targetPressure_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.PC_ProcessTime_edit = QPlainTextEdit(self.page_3)
        self.PC_ProcessTime_edit.setObjectName(u"PC_ProcessTime_edit")
        self.PC_ProcessTime_edit.setGeometry(QRect(820, 370, 201, 31))
        self.PC_biasV_label = QLabel(self.page_3)
        self.PC_biasV_label.setObjectName(u"PC_biasV_label")
        self.PC_biasV_label.setGeometry(QRect(960, 400, 51, 21))
        self.PC_biasV_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.PC_Stop_button = QPushButton(self.page_3)
        self.PC_Stop_button.setObjectName(u"PC_Stop_button")
        self.PC_Stop_button.setGeometry(QRect(930, 510, 91, 61))
        self.preSputter_remainigTime_edit = QPlainTextEdit(self.page_3)
        self.preSputter_remainigTime_edit.setObjectName(u"preSputter_remainigTime_edit")
        self.preSputter_remainigTime_edit.setGeometry(QRect(560, 240, 201, 31))
        self.preSputter_remainigTime_edit.setReadOnly(True)
        self.preSputter_remainigTime_label = QLabel(self.page_3)
        self.preSputter_remainigTime_label.setObjectName(u"preSputter_remainigTime_label")
        self.preSputter_remainigTime_label.setGeometry(QRect(560, 220, 121, 21))
        self.preSputter_remainigTime_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.PC_Start_button = QPushButton(self.page_3)
        self.PC_Start_button.setObjectName(u"PC_Start_button")
        self.PC_Start_button.setGeometry(QRect(820, 510, 91, 61))
        self.preSputter_Stop_button = QPushButton(self.page_3)
        self.preSputter_Stop_button.setObjectName(u"preSputter_Stop_button")
        self.preSputter_Stop_button.setGeometry(QRect(670, 280, 91, 61))
        self.pc_btnGoCh2 = QPushButton(self.page_3)
        self.pc_btnGoCh2.setObjectName(u"pc_btnGoCh2")
        self.pc_btnGoCh2.setGeometry(QRect(30, 240, 211, 101))
        self.pc_btnGoCh1 = QPushButton(self.page_3)
        self.pc_btnGoCh1.setObjectName(u"pc_btnGoCh1")
        self.pc_btnGoCh1.setGeometry(QRect(30, 130, 211, 101))
        self.TSP_basePressure_edit = QPlainTextEdit(self.page_3)
        self.TSP_basePressure_edit.setObjectName(u"TSP_basePressure_edit")
        self.TSP_basePressure_edit.setGeometry(QRect(300, 240, 201, 31))
        self.TSP_basePressure_edit.setReadOnly(True)
        self.TSP_nowCycle_label = QLabel(self.page_3)
        self.TSP_nowCycle_label.setObjectName(u"TSP_nowCycle_label")
        self.TSP_nowCycle_label.setGeometry(QRect(410, 120, 81, 21))
        self.TSP_nowCycle_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.TSP_setCycle_edit = QPlainTextEdit(self.page_3)
        self.TSP_setCycle_edit.setObjectName(u"TSP_setCycle_edit")
        self.TSP_setCycle_edit.setGeometry(QRect(300, 140, 91, 31))
        self.TSP_Start_button = QPushButton(self.page_3)
        self.TSP_Start_button.setObjectName(u"TSP_Start_button")
        self.TSP_Start_button.setGeometry(QRect(300, 280, 91, 61))
        self.TSP_basePressure_label = QLabel(self.page_3)
        self.TSP_basePressure_label.setObjectName(u"TSP_basePressure_label")
        self.TSP_basePressure_label.setGeometry(QRect(300, 220, 161, 21))
        self.TSP_basePressure_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.pc_TSP_label = QLabel(self.page_3)
        self.pc_TSP_label.setObjectName(u"pc_TSP_label")
        self.pc_TSP_label.setGeometry(QRect(310, 60, 181, 51))
        self.pc_TSP_label.setFont(font)
        self.pc_TSP_label.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pc_TSP_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.TSP_setCycle_label = QLabel(self.page_3)
        self.TSP_setCycle_label.setObjectName(u"TSP_setCycle_label")
        self.TSP_setCycle_label.setGeometry(QRect(300, 120, 91, 21))
        self.TSP_setCycle_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.TSP_Stop_button = QPushButton(self.page_3)
        self.TSP_Stop_button.setObjectName(u"TSP_Stop_button")
        self.TSP_Stop_button.setGeometry(QRect(410, 280, 91, 61))
        self.TSP_nowCycle_edit = QPlainTextEdit(self.page_3)
        self.TSP_nowCycle_edit.setObjectName(u"TSP_nowCycle_edit")
        self.TSP_nowCycle_edit.setGeometry(QRect(410, 140, 91, 31))
        self.TSP_nowCycle_edit.setReadOnly(True)
        self.TSP_targetPressure_edit = QPlainTextEdit(self.page_3)
        self.TSP_targetPressure_edit.setObjectName(u"TSP_targetPressure_edit")
        self.TSP_targetPressure_edit.setGeometry(QRect(300, 190, 201, 31))
        self.TSP_targetPressure_label = QLabel(self.page_3)
        self.TSP_targetPressure_label.setObjectName(u"TSP_targetPressure_label")
        self.TSP_targetPressure_label.setGeometry(QRect(300, 170, 151, 21))
        self.TSP_targetPressure_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.pc_logMessage_edit = QPlainTextEdit(self.page_3)
        self.pc_logMessage_edit.setObjectName(u"pc_logMessage_edit")
        self.pc_logMessage_edit.setGeometry(QRect(10, 580, 1061, 371))
        self.pc_logMessage_label = QLabel(self.page_3)
        self.pc_logMessage_label.setObjectName(u"pc_logMessage_label")
        self.pc_logMessage_label.setGeometry(QRect(10, 560, 101, 21))
        self.pc_logMessage_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.PC_useChamber1_radio = QRadioButton(self.page_3)
        self.buttonGroup_2 = QButtonGroup(Form)
        self.buttonGroup_2.setObjectName(u"buttonGroup_2")
        self.buttonGroup_2.addButton(self.PC_useChamber1_radio)
        self.PC_useChamber1_radio.setObjectName(u"PC_useChamber1_radio")
        self.PC_useChamber1_radio.setGeometry(QRect(840, 120, 61, 24))
        self.PC_useChamber1_radio.setAutoExclusive(False)
        self.PC_useChamber2_radio = QRadioButton(self.page_3)
        self.buttonGroup_2.addButton(self.PC_useChamber2_radio)
        self.PC_useChamber2_radio.setObjectName(u"PC_useChamber2_radio")
        self.PC_useChamber2_radio.setGeometry(QRect(940, 120, 61, 24))
        self.PC_useChamber2_radio.setAutoExclusive(False)
        self.pc_processState_edit = QPlainTextEdit(self.page_3)
        self.pc_processState_edit.setObjectName(u"pc_processState_edit")
        self.pc_processState_edit.setGeometry(QRect(30, 0, 1021, 61))
        self.pc_processState_edit.setFont(font)
        self.preSputter_useChamber1_radio = QRadioButton(self.page_3)
        self.buttonGroup = QButtonGroup(Form)
        self.buttonGroup.setObjectName(u"buttonGroup")
        self.buttonGroup.addButton(self.preSputter_useChamber1_radio)
        self.preSputter_useChamber1_radio.setObjectName(u"preSputter_useChamber1_radio")
        self.preSputter_useChamber1_radio.setGeometry(QRect(580, 120, 61, 24))
        self.preSputter_useChamber1_radio.setAutoExclusive(False)
        self.preSputter_useChamber2_radio = QRadioButton(self.page_3)
        self.buttonGroup.addButton(self.preSputter_useChamber2_radio)
        self.preSputter_useChamber2_radio.setObjectName(u"preSputter_useChamber2_radio")
        self.preSputter_useChamber2_radio.setGeometry(QRect(680, 120, 61, 24))
        self.preSputter_useChamber2_radio.setAutoExclusive(False)
        self.PC_processList_button = QPushButton(self.page_3)
        self.PC_processList_button.setObjectName(u"PC_processList_button")
        self.PC_processList_button.setGeometry(QRect(960, 450, 61, 51))
        self.Power_Select_button = QPushButton(self.page_3)
        self.Power_Select_button.setObjectName(u"Power_Select_button")
        self.Power_Select_button.setGeometry(QRect(30, 350, 101, 101))
        self.Power_Select_button.setCheckable(True)
        self.Power_Select_button.setChecked(False)  # 기본 OFF
        # 눌림 상태에 따라 라벨 변경
        self.Power_Select_button.toggled.connect(
            lambda c: self.Power_Select_button.setText("Power\nSelect: ON" if c else "Power\nSelect: OFF")
        )
        self.Server_button = QPushButton(self.page_3)   # ✅ (추가) Server 버튼 1개
        self.Server_button.setObjectName(u"Server_button")   # ← ID(오브젝트명) 동일
        self.Server_button.setGeometry(QRect(140, 350, 101, 101))
        self.stackedWidget.addWidget(self.page_3)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.ch1_processList_button = QPushButton(self.page)
        self.ch1_processList_button.setObjectName(u"ch1_processList_button")
        self.ch1_processList_button.setGeometry(QRect(100, 770, 111, 31))
        self.ch1_Power_edit = QPlainTextEdit(self.page)
        self.ch1_Power_edit.setObjectName(u"ch1_Power_edit")
        self.ch1_Power_edit.setGeometry(QRect(10, 730, 61, 31))
        self.ch1_Power_edit.setReadOnly(True)
        self.ch1_shutterDelay_label = QLabel(self.page)
        self.ch1_shutterDelay_label.setObjectName(u"ch1_shutterDelay_label")
        self.ch1_shutterDelay_label.setGeometry(QRect(10, 560, 141, 21))
        self.ch1_shutterDelay_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch1_Current_label = QLabel(self.page)
        self.ch1_Current_label.setObjectName(u"ch1_Current_label")
        self.ch1_Current_label.setGeometry(QRect(150, 710, 51, 21))
        self.ch1_Current_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch1_Power_label = QLabel(self.page)
        self.ch1_Power_label.setObjectName(u"ch1_Power_label")
        self.ch1_Power_label.setGeometry(QRect(10, 710, 51, 21))
        self.ch1_Power_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch1_dcPulseDutyCycle_edit = QPlainTextEdit(self.page)
        self.ch1_dcPulseDutyCycle_edit.setObjectName(u"ch1_dcPulseDutyCycle_edit")
        self.ch1_dcPulseDutyCycle_edit.setGeometry(QRect(10, 530, 201, 31))
        self.ch1_dcPulseDutyCycle_label = QLabel(self.page)
        self.ch1_dcPulseDutyCycle_label.setObjectName(u"ch1_dcPulseDutyCycle_label")
        self.ch1_dcPulseDutyCycle_label.setGeometry(QRect(10, 510, 201, 21))
        self.ch1_dcPulseDutyCycle_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch1_Sputtering_label = QLabel(self.page)
        self.ch1_Sputtering_label.setObjectName(u"ch1_Sputtering_label")
        self.ch1_Sputtering_label.setGeometry(QRect(10, 60, 201, 51))
        font1 = QFont()
        font1.setPointSize(20)
        self.ch1_Sputtering_label.setFont(font1)
        self.ch1_Sputtering_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_Voltage_label = QLabel(self.page)
        self.ch1_Voltage_label.setObjectName(u"ch1_Voltage_label")
        self.ch1_Voltage_label.setGeometry(QRect(80, 710, 61, 21))
        self.ch1_Voltage_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        # --- Pulse type selector (RF / DC) ---
        self.ch1_pulsePower_group = QButtonGroup(Form)
        self.ch1_pulsePower_group.setExclusive(True)

        self.ch1_rfPulsePower_checkbox = QRadioButton(self.page)
        self.ch1_rfPulsePower_checkbox.setObjectName(u"ch1_rfPulsePower_checkbox")
        self.ch1_rfPulsePower_checkbox.setGeometry(QRect(10, 409, 90, 24))
        self.ch1_pulsePower_group.addButton(self.ch1_rfPulsePower_checkbox)

        self.ch1_dcPulsePower_checkbox = QRadioButton(self.page)
        self.ch1_dcPulsePower_checkbox.setObjectName(u"ch1_dcPulsePower_checkbox")
        self.ch1_dcPulsePower_checkbox.setGeometry(QRect(105, 409, 105, 24))
        self.ch1_pulsePower_group.addButton(self.ch1_dcPulsePower_checkbox)

        self.ch1_integrationTime_label = QLabel(self.page)
        self.ch1_integrationTime_label.setObjectName(u"ch1_integrationTime_label")
        self.ch1_integrationTime_label.setGeometry(QRect(10, 160, 151, 21))
        self.ch1_integrationTime_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_basePressure_label = QLabel(self.page)
        self.ch1_basePressure_label.setObjectName(u"ch1_basePressure_label")
        self.ch1_basePressure_label.setGeometry(QRect(10, 110, 141, 21))
        self.ch1_basePressure_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_gasFlow_label = QLabel(self.page)
        self.ch1_gasFlow_label.setObjectName(u"ch1_gasFlow_label")
        self.ch1_gasFlow_label.setGeometry(QRect(10, 290, 121, 21))
        self.ch1_gasFlow_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_forP_edit = QPlainTextEdit(self.page)
        self.ch1_forP_edit.setObjectName(u"ch1_forP_edit")
        self.ch1_forP_edit.setGeometry(QRect(10, 680, 91, 31))
        self.ch1_forP_edit.setReadOnly(True)

        self.ch1_gunTarget_name = QPlainTextEdit(self.page)
        self.ch1_gunTarget_name.setObjectName(u"ch1_gunTarget_name")
        self.ch1_gunTarget_name.setGeometry(QRect(10, 260, 201, 31))

        self.ch1_basePressure_edit = QPlainTextEdit(self.page)
        self.ch1_basePressure_edit.setObjectName(u"ch1_basePressure_edit")
        self.ch1_basePressure_edit.setGeometry(QRect(10, 130, 201, 31))

        self.ch1_processTime_edit = QPlainTextEdit(self.page)
        self.ch1_processTime_edit.setObjectName(u"ch1_processTime_edit")
        self.ch1_processTime_edit.setGeometry(QRect(10, 630, 201, 31))

        self.ch1_mainShutter_checkbox = QCheckBox(self.page)
        self.ch1_mainShutter_checkbox.setObjectName(u"ch1_mainShutter_checkbox")
        self.ch1_mainShutter_checkbox.setGeometry(QRect(10, 210, 101, 24))

        self.ch1_dcPulseFreq_edit = QPlainTextEdit(self.page)
        self.ch1_dcPulseFreq_edit.setObjectName(u"ch1_dcPulseFreq_edit")
        self.ch1_dcPulseFreq_edit.setGeometry(QRect(10, 480, 201, 31))

        self.ch1_refP_edit = QPlainTextEdit(self.page)
        self.ch1_refP_edit.setObjectName(u"ch1_refP_edit")
        self.ch1_refP_edit.setGeometry(QRect(120, 680, 91, 31))
        self.ch1_refP_edit.setReadOnly(True)

        self.ch1_logMessage_edit = QPlainTextEdit(self.page)
        self.ch1_logMessage_edit.setObjectName(u"ch1_logMessage_edit")
        self.ch1_logMessage_edit.setGeometry(QRect(230, 790, 841, 151))

        self.ch1_powerSelect_checkbox = QCheckBox(self.page)
        self.ch1_powerSelect_checkbox.setObjectName(u"ch1_powerSelect_checkbox")
        self.ch1_powerSelect_checkbox.setGeometry(QRect(120, 210, 101, 24))

        self.ch1_Ar_checkbox = QCheckBox(self.page)
        self.ch1_Ar_checkbox.setObjectName(u"ch1_Ar_checkbox")
        self.ch1_Ar_checkbox.setGeometry(QRect(10, 310, 41, 24))

        self.ch1_dcPulseFreq_label = QLabel(self.page)
        self.ch1_dcPulseFreq_label.setObjectName(u"ch1_dcPulseFreq_label")
        self.ch1_dcPulseFreq_label.setGeometry(QRect(10, 460, 201, 21))
        self.ch1_dcPulseFreq_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_shutterDelay_edit = QPlainTextEdit(self.page)
        self.ch1_shutterDelay_edit.setObjectName(u"ch1_shutterDelay_edit")
        self.ch1_shutterDelay_edit.setGeometry(QRect(10, 580, 201, 31))

        self.ch1_workingPressure_label = QLabel(self.page)
        self.ch1_workingPressure_label.setObjectName(u"ch1_workingPressure_label")
        self.ch1_workingPressure_label.setGeometry(QRect(10, 360, 181, 21))
        self.ch1_workingPressure_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_forP_label = QLabel(self.page)
        self.ch1_forP_label.setObjectName(u"ch1_forP_label")
        self.ch1_forP_label.setGeometry(QRect(10, 660, 51, 21))
        self.ch1_forP_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_processList_label = QLabel(self.page)
        self.ch1_processList_label.setObjectName(u"ch1_processList_label")
        self.ch1_processList_label.setGeometry(QRect(10, 770, 81, 21))
        self.ch1_processList_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_o2Flow_edit = QPlainTextEdit(self.page)
        self.ch1_o2Flow_edit.setObjectName(u"ch1_o2Flow_edit")
        self.ch1_o2Flow_edit.setGeometry(QRect(110, 330, 101, 31))

        self.ch1_dcPulsePower_edit = QPlainTextEdit(self.page)
        self.ch1_dcPulsePower_edit.setObjectName(u"ch1_dcPulsePower_edit")
        self.ch1_dcPulsePower_edit.setGeometry(QRect(10, 430, 201, 31))

        self.ch1_Voltage_edit = QPlainTextEdit(self.page)
        self.ch1_Voltage_edit.setObjectName(u"ch1_Voltage_edit")
        self.ch1_Voltage_edit.setGeometry(QRect(80, 730, 61, 31))
        self.ch1_Voltage_edit.setReadOnly(True)

        self.ch1_rgaGraph_label = QLabel(self.page)
        self.ch1_rgaGraph_label.setObjectName(u"ch1_rgaGraph_label")
        self.ch1_rgaGraph_label.setGeometry(QRect(230, 70, 81, 21))
        self.ch1_rgaGraph_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_workingPressure_edit = QPlainTextEdit(self.page)
        self.ch1_workingPressure_edit.setObjectName(u"ch1_workingPressure_edit")
        self.ch1_workingPressure_edit.setGeometry(QRect(10, 380, 201, 31))

        self.ch1_Stop_button = QPushButton(self.page)
        self.ch1_Stop_button.setObjectName(u"ch1_Stop_button")
        self.ch1_Stop_button.setGeometry(QRect(120, 830, 91, 61))

        self.ch1_gunTargetName_label = QLabel(self.page)
        self.ch1_gunTargetName_label.setObjectName(u"ch1_gunTargetName_label")
        self.ch1_gunTargetName_label.setGeometry(QRect(10, 240, 131, 21))
        self.ch1_gunTargetName_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_Current_edit = QPlainTextEdit(self.page)
        self.ch1_Current_edit.setObjectName(u"ch1_Current_edit")
        self.ch1_Current_edit.setGeometry(QRect(150, 730, 61, 31))
        self.ch1_Current_edit.setReadOnly(True)

        self.ch1_oesGraph_widget = QWidget(self.page)
        self.ch1_oesGraph_widget.setObjectName(u"ch1_oesGraph_widget")
        self.ch1_oesGraph_widget.setGeometry(QRect(230, 420, 841, 351))

        self.ch1_Start_button = QPushButton(self.page)
        self.ch1_Start_button.setObjectName(u"ch1_Start_button")
        self.ch1_Start_button.setGeometry(QRect(10, 830, 91, 61))

        self.ch1_intergrationTime_edit = QPlainTextEdit(self.page)
        self.ch1_intergrationTime_edit.setObjectName(u"ch1_intergrationTime_edit")
        self.ch1_intergrationTime_edit.setGeometry(QRect(10, 180, 201, 31))

        self.ch1_refP_label = QLabel(self.page)
        self.ch1_refP_label.setObjectName(u"ch1_refP_label")
        self.ch1_refP_label.setGeometry(QRect(120, 660, 51, 21))
        self.ch1_refP_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_arFlow_edit = QPlainTextEdit(self.page)
        self.ch1_arFlow_edit.setObjectName(u"ch1_arFlow_edit")
        self.ch1_arFlow_edit.setGeometry(QRect(10, 330, 101, 31))

        self.ch1_processTime_label = QLabel(self.page)
        self.ch1_processTime_label.setObjectName(u"ch1_processTime_label")
        self.ch1_processTime_label.setGeometry(QRect(10, 610, 141, 21))
        self.ch1_processTime_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_oesGraph_label = QLabel(self.page)
        self.ch1_oesGraph_label.setObjectName(u"ch1_oesGraph_label")
        self.ch1_oesGraph_label.setGeometry(QRect(230, 400, 81, 21))
        self.ch1_oesGraph_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_rgaGraph_widget = QWidget(self.page)
        self.ch1_rgaGraph_widget.setObjectName(u"ch1_rgaGraph_widget")
        self.ch1_rgaGraph_widget.setGeometry(QRect(230, 90, 841, 311))

        self.ch1_O2_checkbox = QCheckBox(self.page)
        self.ch1_O2_checkbox.setObjectName(u"ch1_O2_checkbox")
        self.ch1_O2_checkbox.setGeometry(QRect(110, 310, 41, 24))

        self.ch1_logMessage_label = QLabel(self.page)
        self.ch1_logMessage_label.setObjectName(u"ch1_logMessage_label")
        self.ch1_logMessage_label.setGeometry(QRect(230, 770, 101, 21))
        self.ch1_logMessage_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.ch1_processState_edit = QPlainTextEdit(self.page)
        self.ch1_processState_edit.setObjectName(u"ch1_processState_edit")
        self.ch1_processState_edit.setGeometry(QRect(230, 0, 841, 61))
        self.ch1_processState_edit.setFont(font)

        self.ch1_btnGoPC = QPushButton(self.page)
        self.ch1_btnGoPC.setObjectName(u"ch1_btnGoPC")
        self.ch1_btnGoPC.setGeometry(QRect(120, 0, 91, 61))

        self.ch1_btnGoCh2 = QPushButton(self.page)
        self.ch1_btnGoCh2.setObjectName(u"ch1_btnGoCh2")
        self.ch1_btnGoCh2.setGeometry(QRect(10, 0, 91, 61))
        
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.ch2_g3Target_name = QPlainTextEdit(self.page_2)
        self.ch2_g3Target_name.setObjectName(u"ch2_g3Target_name")
        self.ch2_g3Target_name.setGeometry(QRect(150, 280, 61, 31))
        self.ch2_O2_checkbox = QCheckBox(self.page_2)
        self.ch2_O2_checkbox.setObjectName(u"ch2_O2_checkbox")
        self.ch2_O2_checkbox.setGeometry(QRect(80, 330, 41, 24))
        self.ch2_integrationTime_edit = QPlainTextEdit(self.page_2)
        self.ch2_integrationTime_edit.setObjectName(u"ch2_integrationTime_edit")
        self.ch2_integrationTime_edit.setGeometry(QRect(10, 180, 201, 31))
        self.ch2_rfPulseFreq_edit = QPlainTextEdit(self.page_2)
        self.ch2_rfPulseFreq_edit.setObjectName(u"ch2_rfPulseFreq_edit")
        self.ch2_rfPulseFreq_edit.setGeometry(QRect(10, 500, 201, 31))
        self.ch2_Voltage_label = QLabel(self.page_2)
        self.ch2_Voltage_label.setObjectName(u"ch2_Voltage_label")
        self.ch2_Voltage_label.setGeometry(QRect(80, 780, 61, 21))
        self.ch2_Voltage_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_Ar_checkbox = QCheckBox(self.page_2)
        self.ch2_Ar_checkbox.setObjectName(u"ch2_Ar_checkbox")
        self.ch2_Ar_checkbox.setGeometry(QRect(10, 330, 41, 24))
        self.ch2_o2Flow_edit = QPlainTextEdit(self.page_2)
        self.ch2_o2Flow_edit.setObjectName(u"ch2_o2Flow_edit")
        self.ch2_o2Flow_edit.setGeometry(QRect(80, 350, 61, 31))
        self.ch2_processTime_edit = QPlainTextEdit(self.page_2)
        self.ch2_processTime_edit.setObjectName(u"ch2_processTime_edit")
        self.ch2_processTime_edit.setGeometry(QRect(10, 700, 201, 31))
        self.ch2_oesGraph_label = QLabel(self.page_2)
        self.ch2_oesGraph_label.setObjectName(u"ch2_oesGraph_label")
        self.ch2_oesGraph_label.setGeometry(QRect(230, 400, 131, 21))
        self.ch2_oesGraph_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_shutterDelay_label = QLabel(self.page_2)
        self.ch2_shutterDelay_label.setObjectName(u"ch2_shutterDelay_label")
        self.ch2_shutterDelay_label.setGeometry(QRect(10, 630, 141, 21))
        self.ch2_shutterDelay_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_rgaGraph_label = QLabel(self.page_2)
        self.ch2_rgaGraph_label.setObjectName(u"ch2_rgaGraph_label")
        self.ch2_rgaGraph_label.setGeometry(QRect(230, 70, 131, 21))
        self.ch2_rgaGraph_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_N2_checkbox = QCheckBox(self.page_2)
        self.ch2_N2_checkbox.setObjectName(u"ch2_N2_checkbox")
        self.ch2_N2_checkbox.setGeometry(QRect(150, 330, 41, 24))
        self.ch2_basePressure_label = QLabel(self.page_2)
        self.ch2_basePressure_label.setObjectName(u"ch2_basePressure_label")
        self.ch2_basePressure_label.setGeometry(QRect(10, 110, 141, 21))
        self.ch2_basePressure_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_rfPulseDutyCycle_label = QLabel(self.page_2)
        self.ch2_rfPulseDutyCycle_label.setObjectName(u"ch2_rfPulseDutyCycle_label")
        self.ch2_rfPulseDutyCycle_label.setGeometry(QRect(10, 530, 171, 21))
        self.ch2_rfPulseDutyCycle_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_powerSelect_checkbox = QCheckBox(self.page_2)
        self.ch2_powerSelect_checkbox.setObjectName(u"ch2_powerSelect_checkbox")
        self.ch2_powerSelect_checkbox.setGeometry(QRect(120, 210, 101, 24))
        self.ch2_Voltage_edit = QPlainTextEdit(self.page_2)
        self.ch2_Voltage_edit.setObjectName(u"ch2_Voltage_edit")
        self.ch2_Voltage_edit.setGeometry(QRect(80, 800, 61, 31))
        self.ch2_Voltage_edit.setReadOnly(True)
        self.ch2_workingPressure_label = QLabel(self.page_2)
        self.ch2_workingPressure_label.setObjectName(u"ch2_workingPressure_label")
        self.ch2_workingPressure_label.setGeometry(QRect(10, 380, 181, 21))
        self.ch2_workingPressure_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_processTime_label = QLabel(self.page_2)
        self.ch2_processTime_label.setObjectName(u"ch2_processTime_label")
        self.ch2_processTime_label.setGeometry(QRect(10, 680, 141, 21))
        self.ch2_processTime_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_oesGraph_widget = QWidget(self.page_2)
        self.ch2_oesGraph_widget.setObjectName(u"ch2_oesGraph_widget")
        self.ch2_oesGraph_widget.setGeometry(QRect(230, 420, 841, 351))
        self.ch2_forP_edit = QPlainTextEdit(self.page_2)
        self.ch2_forP_edit.setObjectName(u"ch2_forP_edit")
        self.ch2_forP_edit.setGeometry(QRect(10, 750, 91, 31))
        self.ch2_forP_edit.setReadOnly(True)
        self.ch2_gasFlow_label = QLabel(self.page_2)
        self.ch2_gasFlow_label.setObjectName(u"ch2_gasFlow_label")
        self.ch2_gasFlow_label.setGeometry(QRect(10, 310, 111, 21))
        self.ch2_gasFlow_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_g1Target_name = QPlainTextEdit(self.page_2)
        self.ch2_g1Target_name.setObjectName(u"ch2_g1Target_name")
        self.ch2_g1Target_name.setGeometry(QRect(10, 280, 61, 31))
        self.ch2_forP_label = QLabel(self.page_2)
        self.ch2_forP_label.setObjectName(u"ch2_forP_label")
        self.ch2_forP_label.setGeometry(QRect(10, 730, 51, 21))
        self.ch2_forP_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_Start_button = QPushButton(self.page_2)
        self.ch2_Start_button.setObjectName(u"ch2_Start_button")
        self.ch2_Start_button.setGeometry(QRect(10, 880, 91, 61))
        self.ch2_G2_checkbox = QCheckBox(self.page_2)
        self.ch2_G2_checkbox.setObjectName(u"ch2_G2_checkbox")
        self.ch2_G2_checkbox.setGeometry(QRect(80, 260, 41, 24))
        self.ch2_logMessage_edit = QPlainTextEdit(self.page_2)
        self.ch2_logMessage_edit.setObjectName(u"ch2_logMessage_edit")
        self.ch2_logMessage_edit.setGeometry(QRect(230, 790, 841, 151))
        self.ch2_Current_edit = QPlainTextEdit(self.page_2)
        self.ch2_Current_edit.setObjectName(u"ch2_Current_edit")
        self.ch2_Current_edit.setGeometry(QRect(150, 800, 61, 31))
        self.ch2_Current_edit.setReadOnly(True)
        self.ch2_g2Target_name = QPlainTextEdit(self.page_2)
        self.ch2_g2Target_name.setObjectName(u"ch2_g2Target_name")
        self.ch2_g2Target_name.setGeometry(QRect(80, 280, 61, 31))
        self.ch2_G3_checkbox = QCheckBox(self.page_2)
        self.ch2_G3_checkbox.setObjectName(u"ch2_G3_checkbox")
        self.ch2_G3_checkbox.setGeometry(QRect(150, 260, 41, 24))
        self.ch2_integrationTime_label = QLabel(self.page_2)
        self.ch2_integrationTime_label.setObjectName(u"ch2_integrationTime_label")
        self.ch2_integrationTime_label.setGeometry(QRect(10, 160, 151, 21))
        self.ch2_integrationTime_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_processList_button = QPushButton(self.page_2)
        self.ch2_processList_button.setObjectName(u"ch2_processList_button")
        self.ch2_processList_button.setGeometry(QRect(100, 840, 111, 31))
        self.ch2_rgaGraph_widget = QWidget(self.page_2)
        self.ch2_rgaGraph_widget.setObjectName(u"ch2_rgaGraph_widget")
        self.ch2_rgaGraph_widget.setGeometry(QRect(230, 90, 841, 311))
        self.ch2_mainShutter_checkbox = QCheckBox(self.page_2)
        self.ch2_mainShutter_checkbox.setObjectName(u"ch2_mainShutter_checkbox")
        self.ch2_mainShutter_checkbox.setGeometry(QRect(10, 210, 101, 24))
        self.ch2_n2Flow_edit = QPlainTextEdit(self.page_2)
        self.ch2_n2Flow_edit.setObjectName(u"ch2_n2Flow_edit")
        self.ch2_n2Flow_edit.setGeometry(QRect(150, 350, 61, 31))
        self.ch2_arFlow_edit = QPlainTextEdit(self.page_2)
        self.ch2_arFlow_edit.setObjectName(u"ch2_arFlow_edit")
        self.ch2_arFlow_edit.setGeometry(QRect(10, 350, 61, 31))
        self.ch2_workingPressure_edit = QPlainTextEdit(self.page_2)
        self.ch2_workingPressure_edit.setObjectName(u"ch2_workingPressure_edit")
        self.ch2_workingPressure_edit.setGeometry(QRect(10, 400, 201, 31))
        self.ch2_rfPulseFreq_label = QLabel(self.page_2)
        self.ch2_rfPulseFreq_label.setObjectName(u"ch2_rfPulseFreq_label")
        self.ch2_rfPulseFreq_label.setGeometry(QRect(10, 480, 181, 21))
        self.ch2_rfPulseFreq_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_gunTargetName_label = QLabel(self.page_2)
        self.ch2_gunTargetName_label.setObjectName(u"ch2_gunTargetName_label")
        self.ch2_gunTargetName_label.setGeometry(QRect(10, 240, 131, 21))
        self.ch2_gunTargetName_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_rfPulsePower_edit = QPlainTextEdit(self.page_2)
        self.ch2_rfPulsePower_edit.setObjectName(u"ch2_rfPulsePower_edit")
        self.ch2_rfPulsePower_edit.setGeometry(QRect(10, 450, 201, 31))
        self.ch2_shutterDelay_edit = QPlainTextEdit(self.page_2)
        self.ch2_shutterDelay_edit.setObjectName(u"ch2_shutterDelay_edit")
        self.ch2_shutterDelay_edit.setGeometry(QRect(10, 650, 201, 31))
        self.ch2_G1_checkbox = QCheckBox(self.page_2)
        self.ch2_G1_checkbox.setObjectName(u"ch2_G1_checkbox")
        self.ch2_G1_checkbox.setGeometry(QRect(10, 260, 41, 24))
        self.ch2_rfPulseDutyCycle_edit = QPlainTextEdit(self.page_2)
        self.ch2_rfPulseDutyCycle_edit.setObjectName(u"ch2_rfPulseDutyCycle_edit")
        self.ch2_rfPulseDutyCycle_edit.setGeometry(QRect(10, 550, 201, 31))
        self.ch2_refP_label = QLabel(self.page_2)
        self.ch2_refP_label.setObjectName(u"ch2_refP_label")
        self.ch2_refP_label.setGeometry(QRect(120, 730, 51, 21))
        self.ch2_refP_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_Stop_button = QPushButton(self.page_2)
        self.ch2_Stop_button.setObjectName(u"ch2_Stop_button")
        self.ch2_Stop_button.setGeometry(QRect(120, 880, 91, 61))
        self.ch2_processList_label = QLabel(self.page_2)
        self.ch2_processList_label.setObjectName(u"ch2_processList_label")
        self.ch2_processList_label.setGeometry(QRect(10, 840, 81, 21))
        self.ch2_processList_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_Sputtering_label = QLabel(self.page_2)
        self.ch2_Sputtering_label.setObjectName(u"ch2_Sputtering_label")
        self.ch2_Sputtering_label.setGeometry(QRect(10, 60, 201, 51))
        self.ch2_Sputtering_label.setFont(font1)
        self.ch2_Sputtering_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ch2_Power_label = QLabel(self.page_2)
        self.ch2_Power_label.setObjectName(u"ch2_Power_label")
        self.ch2_Power_label.setGeometry(QRect(10, 780, 51, 21))
        self.ch2_Power_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_Current_label = QLabel(self.page_2)
        self.ch2_Current_label.setObjectName(u"ch2_Current_label")
        self.ch2_Current_label.setGeometry(QRect(150, 780, 51, 21))
        self.ch2_Current_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_basePressure_edit = QPlainTextEdit(self.page_2)
        self.ch2_basePressure_edit.setObjectName(u"ch2_basePressure_edit")
        self.ch2_basePressure_edit.setGeometry(QRect(10, 130, 201, 31))
        self.ch2_rfPulsePower_checkbox = QCheckBox(self.page_2)
        self.ch2_rfPulsePower_checkbox.setObjectName(u"ch2_rfPulsePower_checkbox")
        self.ch2_rfPulsePower_checkbox.setGeometry(QRect(10, 430, 161, 24))
        self.ch2_refP_edit = QPlainTextEdit(self.page_2)
        self.ch2_refP_edit.setObjectName(u"ch2_refP_edit")
        self.ch2_refP_edit.setGeometry(QRect(120, 750, 91, 31))
        self.ch2_refP_edit.setReadOnly(True)
        self.ch2_Power_edit = QPlainTextEdit(self.page_2)
        self.ch2_Power_edit.setObjectName(u"ch2_Power_edit")
        self.ch2_Power_edit.setGeometry(QRect(10, 800, 61, 31))
        self.ch2_Power_edit.setReadOnly(True)
        self.ch2_logMessage_label = QLabel(self.page_2)
        self.ch2_logMessage_label.setObjectName(u"ch2_logMessage_label")
        self.ch2_logMessage_label.setGeometry(QRect(230, 770, 131, 21))
        self.ch2_logMessage_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ch2_processState_edit = QPlainTextEdit(self.page_2)
        self.ch2_processState_edit.setObjectName(u"ch2_processState_edit")
        self.ch2_processState_edit.setGeometry(QRect(230, 0, 841, 61))
        self.ch2_processState_edit.setFont(font)
        self.ch2_btnGoPC = QPushButton(self.page_2)
        self.ch2_btnGoPC.setObjectName(u"ch2_btnGoPC")
        self.ch2_btnGoPC.setGeometry(QRect(120, 0, 91, 61))
        self.ch2_btnGoCh1 = QPushButton(self.page_2)
        self.ch2_btnGoCh1.setObjectName(u"ch2_btnGoCh1")
        self.ch2_btnGoCh1.setGeometry(QRect(10, 0, 91, 61))
        self.ch2_dcPower_edit = QPlainTextEdit(self.page_2)
        self.ch2_dcPower_edit.setObjectName(u"ch2_dcPower_edit")
        self.ch2_dcPower_edit.setGeometry(QRect(10, 600, 101, 31))
        self.ch2_dcPower_checkbox = QCheckBox(self.page_2)
        self.ch2_dcPower_checkbox.setObjectName(u"ch2_dcPower_checkbox")
        self.ch2_dcPower_checkbox.setGeometry(QRect(10, 580, 101, 24))
        self.ch2_rfPower_edit = QPlainTextEdit(self.page_2)
        self.ch2_rfPower_edit.setObjectName(u"ch2_rfPower_edit")
        self.ch2_rfPower_edit.setGeometry(QRect(110, 600, 101, 31))
        self.ch2_rfPower_checkbox = QCheckBox(self.page_2)
        self.ch2_rfPower_checkbox.setObjectName(u"ch2_rfPower_checkbox")
        self.ch2_rfPower_checkbox.setGeometry(QRect(110, 580, 101, 24))
        self.stackedWidget.addWidget(self.page_2)
        QWidget.setTabOrder(self.pc_processState_edit, self.pc_btnGoCh1)
        QWidget.setTabOrder(self.pc_btnGoCh1, self.pc_btnGoCh2)
        QWidget.setTabOrder(self.pc_btnGoCh2, self.TSP_setCycle_edit)
        QWidget.setTabOrder(self.TSP_setCycle_edit, self.TSP_targetPressure_edit)
        QWidget.setTabOrder(self.TSP_targetPressure_edit, self.TSP_Start_button)
        QWidget.setTabOrder(self.TSP_Start_button, self.TSP_Stop_button)
        QWidget.setTabOrder(self.TSP_Stop_button, self.preSputter_useChamber1_radio)
        QWidget.setTabOrder(self.preSputter_useChamber1_radio, self.preSputter_useChamber2_radio)
        QWidget.setTabOrder(self.preSputter_useChamber2_radio, self.preSputter_SetTime_edit)
        QWidget.setTabOrder(self.preSputter_SetTime_edit, self.preSputter_Start_button)
        QWidget.setTabOrder(self.preSputter_Start_button, self.preSputter_Stop_button)
        QWidget.setTabOrder(self.preSputter_Stop_button, self.PC_useChamber1_radio)
        QWidget.setTabOrder(self.PC_useChamber1_radio, self.PC_useChamber2_radio)
        QWidget.setTabOrder(self.PC_useChamber2_radio, self.PC_targetPressure_edit)
        QWidget.setTabOrder(self.PC_targetPressure_edit, self.PC_gasFlow_edit)
        QWidget.setTabOrder(self.PC_gasFlow_edit, self.PC_workingPressure_edit)
        QWidget.setTabOrder(self.PC_workingPressure_edit, self.PC_rfPower_edit)
        QWidget.setTabOrder(self.PC_rfPower_edit, self.PC_ProcessTime_edit)
        QWidget.setTabOrder(self.PC_ProcessTime_edit, self.PC_Start_button)
        QWidget.setTabOrder(self.PC_Start_button, self.PC_Stop_button)
        QWidget.setTabOrder(self.PC_Stop_button, self.pc_logMessage_edit)
        QWidget.setTabOrder(self.pc_logMessage_edit, self.ch1_btnGoCh2)
        QWidget.setTabOrder(self.ch1_btnGoCh2, self.ch1_btnGoPC)
        QWidget.setTabOrder(self.ch1_btnGoPC, self.ch1_basePressure_edit)
        QWidget.setTabOrder(self.ch1_basePressure_edit, self.ch1_intergrationTime_edit)
        QWidget.setTabOrder(self.ch1_intergrationTime_edit, self.ch1_mainShutter_checkbox)
        QWidget.setTabOrder(self.ch1_mainShutter_checkbox, self.ch1_powerSelect_checkbox)
        QWidget.setTabOrder(self.ch1_powerSelect_checkbox, self.ch1_gunTarget_name)
        QWidget.setTabOrder(self.ch1_gunTarget_name, self.ch1_Ar_checkbox)
        QWidget.setTabOrder(self.ch1_Ar_checkbox, self.ch1_O2_checkbox)
        QWidget.setTabOrder(self.ch1_O2_checkbox, self.ch1_arFlow_edit)
        QWidget.setTabOrder(self.ch1_arFlow_edit, self.ch1_o2Flow_edit)
        QWidget.setTabOrder(self.ch1_o2Flow_edit, self.ch1_workingPressure_edit)
        QWidget.setTabOrder(self.ch1_workingPressure_edit, self.ch1_rfPulsePower_checkbox)
        QWidget.setTabOrder(self.ch1_rfPulsePower_checkbox, self.ch1_dcPulsePower_checkbox)
        QWidget.setTabOrder(self.ch1_dcPulsePower_checkbox, self.ch1_dcPulsePower_edit)
        QWidget.setTabOrder(self.ch1_dcPulsePower_edit, self.ch1_dcPulseFreq_edit)
        QWidget.setTabOrder(self.ch1_dcPulseFreq_edit, self.ch1_dcPulseDutyCycle_edit)
        QWidget.setTabOrder(self.ch1_dcPulseDutyCycle_edit, self.ch1_shutterDelay_edit)
        QWidget.setTabOrder(self.ch1_shutterDelay_edit, self.ch1_processTime_edit)
        QWidget.setTabOrder(self.ch1_processTime_edit, self.ch1_processList_button)
        QWidget.setTabOrder(self.ch1_processList_button, self.ch1_Start_button)
        QWidget.setTabOrder(self.ch1_Start_button, self.ch1_Stop_button)
        QWidget.setTabOrder(self.ch1_Stop_button, self.ch1_processState_edit)
        QWidget.setTabOrder(self.ch1_processState_edit, self.ch1_logMessage_edit)
        QWidget.setTabOrder(self.ch1_logMessage_edit, self.ch2_btnGoCh1)
        QWidget.setTabOrder(self.ch2_btnGoCh1, self.ch2_btnGoPC)
        QWidget.setTabOrder(self.ch2_btnGoPC, self.ch2_basePressure_edit)
        QWidget.setTabOrder(self.ch2_basePressure_edit, self.ch2_integrationTime_edit)
        QWidget.setTabOrder(self.ch2_integrationTime_edit, self.ch2_mainShutter_checkbox)
        QWidget.setTabOrder(self.ch2_mainShutter_checkbox, self.ch2_powerSelect_checkbox)
        QWidget.setTabOrder(self.ch2_powerSelect_checkbox, self.ch2_G1_checkbox)
        QWidget.setTabOrder(self.ch2_G1_checkbox, self.ch2_G2_checkbox)
        QWidget.setTabOrder(self.ch2_G2_checkbox, self.ch2_G3_checkbox)
        QWidget.setTabOrder(self.ch2_G3_checkbox, self.ch2_g1Target_name)
        QWidget.setTabOrder(self.ch2_g1Target_name, self.ch2_g2Target_name)
        QWidget.setTabOrder(self.ch2_g2Target_name, self.ch2_g3Target_name)
        QWidget.setTabOrder(self.ch2_g3Target_name, self.ch2_Ar_checkbox)
        QWidget.setTabOrder(self.ch2_Ar_checkbox, self.ch2_O2_checkbox)
        QWidget.setTabOrder(self.ch2_O2_checkbox, self.ch2_N2_checkbox)
        QWidget.setTabOrder(self.ch2_N2_checkbox, self.ch2_arFlow_edit)
        QWidget.setTabOrder(self.ch2_arFlow_edit, self.ch2_o2Flow_edit)
        QWidget.setTabOrder(self.ch2_o2Flow_edit, self.ch2_n2Flow_edit)
        QWidget.setTabOrder(self.ch2_n2Flow_edit, self.ch2_workingPressure_edit)
        QWidget.setTabOrder(self.ch2_workingPressure_edit, self.ch2_rfPulsePower_checkbox)
        QWidget.setTabOrder(self.ch2_rfPulsePower_checkbox, self.ch2_rfPulsePower_edit)
        QWidget.setTabOrder(self.ch2_rfPulsePower_edit, self.ch2_rfPulseFreq_edit)
        QWidget.setTabOrder(self.ch2_rfPulseFreq_edit, self.ch2_rfPulseDutyCycle_edit)
        QWidget.setTabOrder(self.ch2_rfPulseDutyCycle_edit, self.ch2_dcPower_checkbox)
        QWidget.setTabOrder(self.ch2_dcPower_checkbox, self.ch2_dcPower_edit)
        QWidget.setTabOrder(self.ch2_dcPower_edit, self.ch2_shutterDelay_edit)
        QWidget.setTabOrder(self.ch2_shutterDelay_edit, self.ch2_processTime_edit)
        QWidget.setTabOrder(self.ch2_processTime_edit, self.ch2_processList_button)
        QWidget.setTabOrder(self.ch2_processList_button, self.ch2_Start_button)
        QWidget.setTabOrder(self.ch2_Start_button, self.ch2_Stop_button)
        QWidget.setTabOrder(self.ch2_Stop_button, self.ch2_processState_edit)
        QWidget.setTabOrder(self.ch2_processState_edit, self.ch2_logMessage_edit)
        QWidget.setTabOrder(self.ch2_logMessage_edit, self.PC_Hum_edit)
        QWidget.setTabOrder(self.PC_Hum_edit, self.preSputter_LeftTime_edit)
        QWidget.setTabOrder(self.preSputter_LeftTime_edit, self.preSputter_remainigTime_edit)
        QWidget.setTabOrder(self.preSputter_remainigTime_edit, self.ch1_forP_edit)
        QWidget.setTabOrder(self.ch1_forP_edit, self.ch1_refP_edit)
        QWidget.setTabOrder(self.ch1_refP_edit, self.ch1_Power_edit)
        QWidget.setTabOrder(self.ch1_Power_edit, self.ch1_Voltage_edit)
        QWidget.setTabOrder(self.ch1_Voltage_edit, self.ch1_Current_edit)
        QWidget.setTabOrder(self.ch1_Current_edit, self.TSP_basePressure_edit)
        QWidget.setTabOrder(self.TSP_basePressure_edit, self.TSP_nowCycle_edit)
        QWidget.setTabOrder(self.TSP_nowCycle_edit, self.ch2_forP_edit)
        QWidget.setTabOrder(self.ch2_forP_edit, self.ch2_refP_edit)
        QWidget.setTabOrder(self.ch2_refP_edit, self.ch2_Power_edit)
        QWidget.setTabOrder(self.ch2_Power_edit, self.ch2_Voltage_edit)
        QWidget.setTabOrder(self.ch2_Voltage_edit, self.ch2_Current_edit)
        QWidget.setTabOrder(self.ch2_Current_edit, self.PC_forP_edit)
        QWidget.setTabOrder(self.PC_forP_edit, self.PC_refP_edit)
        QWidget.setTabOrder(self.PC_refP_edit, self.PC_biasV_edit)
        QWidget.setTabOrder(self.PC_biasV_edit, self.PC_Temp_edit)

        self.retranslateUi(Form)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.PC_rfPower_label.setText(QCoreApplication.translate("Form", u"RF Power [W]", None))
        self.plasmaCleaning_label.setText(QCoreApplication.translate("Form", u"Plasma Cleaning", None))
        self.PC_forP_label.setText(QCoreApplication.translate("Form", u"For. P", None))
        self.preSputter_Start_button.setText(QCoreApplication.translate("Form", u"START", None))
        self.PC_refP_label.setText(QCoreApplication.translate("Form", u"Ref. P", None))
        self.PC_ProcessTime_label.setText(QCoreApplication.translate("Form", u"Process Time [min]", None))
        self.PC_Hum_label.setText(QCoreApplication.translate("Form", u"Hum", None))
        self.pc_preSputter_label.setText(QCoreApplication.translate("Form", u"Pre-Sputter", None))
        self.preSputter_LeftTime_label.setText(QCoreApplication.translate("Form", u"Waiting...", None))
        self.PC_gasFlow_label.setText(QCoreApplication.translate("Form", u"Gas Flow [sccm]", None))
        self.preSputter_SetTime_label.setText(QCoreApplication.translate("Form", u"HH:MM", None))
        self.PC_Temp_label.setText(QCoreApplication.translate("Form", u"Temp", None))
        self.PC_workingPressure_label.setText(QCoreApplication.translate("Form", u"Working Pressure [mTorr]", None))
        self.PC_targetPressure_label.setText(QCoreApplication.translate("Form", u"Base Pressure [Torr]", None))
        self.PC_biasV_label.setText(QCoreApplication.translate("Form", u"Bias V", None))
        self.PC_Stop_button.setText(QCoreApplication.translate("Form", u"STOP", None))
        self.preSputter_remainigTime_label.setText(QCoreApplication.translate("Form", u"Remaining Time", None))
        self.PC_Start_button.setText(QCoreApplication.translate("Form", u"START", None))
        self.preSputter_Stop_button.setText(QCoreApplication.translate("Form", u"STOP", None))
        self.pc_btnGoCh2.setText(QCoreApplication.translate("Form", u"CH.2", None))
        self.pc_btnGoCh1.setText(QCoreApplication.translate("Form", u"CH.1", None))
        self.TSP_nowCycle_label.setText(QCoreApplication.translate("Form", u"# Cycle", None))
        self.TSP_Start_button.setText(QCoreApplication.translate("Form", u"START", None))
        self.TSP_basePressure_label.setText(QCoreApplication.translate("Form", u"U. Base Pressure [Torr]", None))
        self.pc_TSP_label.setText(QCoreApplication.translate("Form", u"TSP", None))
        self.TSP_setCycle_label.setText(QCoreApplication.translate("Form", u"#", None))
        self.TSP_Stop_button.setText(QCoreApplication.translate("Form", u"STOP", None))
        self.TSP_targetPressure_label.setText(QCoreApplication.translate("Form", u"Base Pressure [Torr]", None))
        self.pc_logMessage_label.setText(QCoreApplication.translate("Form", u"Log Message", None))
        self.PC_useChamber1_radio.setText(QCoreApplication.translate("Form", u"CH1", None))
        self.PC_useChamber2_radio.setText(QCoreApplication.translate("Form", u"CH2", None))
        self.pc_processState_edit.setPlainText("")
        self.preSputter_useChamber1_radio.setText(QCoreApplication.translate("Form", u"CH1", None))
        self.preSputter_useChamber2_radio.setText(QCoreApplication.translate("Form", u"CH2", None))
        self.PC_processList_button.setText(QCoreApplication.translate("Form", u"File\n" "Path", None))
        self.Power_Select_button.setText(QCoreApplication.translate("Form", u"Power\n" "Select: OFF", None))
        self.Server_button.setText(QCoreApplication.translate("Form", u"Server", None)) # ✅ (추가) Server 버튼 텍스트
        self.ch1_processList_button.setText(QCoreApplication.translate("Form", u"Select File", None))
        self.ch1_shutterDelay_label.setText(QCoreApplication.translate("Form", u"Shutter Delay [min]", None))
        self.ch1_Current_label.setText(QCoreApplication.translate("Form", u"Current", None))
        self.ch1_Power_label.setText(QCoreApplication.translate("Form", u"Power", None))
        self.ch1_dcPulseDutyCycle_label.setText(QCoreApplication.translate("Form", u"RF/DC Pulse Duty Cycle [%]", None))
        self.ch1_Sputtering_label.setText(QCoreApplication.translate("Form", u"CH.1 Sputtering", None))
        self.ch1_Voltage_label.setText(QCoreApplication.translate("Form", u"Voltage", None))
        self.ch1_rfPulsePower_checkbox.setText(QCoreApplication.translate("Form", u"RF Pulse", None))
        self.ch1_dcPulsePower_checkbox.setText(QCoreApplication.translate("Form", u"DC Pulse", None))
        self.ch1_integrationTime_label.setText(QCoreApplication.translate("Form", u"Integration Time [ms]", None))
        self.ch1_basePressure_label.setText(QCoreApplication.translate("Form", u"Base Pressure [Torr]", None))
        self.ch1_gasFlow_label.setText(QCoreApplication.translate("Form", u"Gas Flow [sccm]", None))
        self.ch1_mainShutter_checkbox.setText(QCoreApplication.translate("Form", u"M.S. Open", None))
        self.ch1_powerSelect_checkbox.setText(QCoreApplication.translate("Form", u"P.W. Select", None))
        self.ch1_Ar_checkbox.setText(QCoreApplication.translate("Form", u"Ar", None))
        self.ch1_dcPulseFreq_label.setText(QCoreApplication.translate("Form", u"RF/DC Pulse Freq [kHz]", None))
        self.ch1_workingPressure_label.setText(QCoreApplication.translate("Form", u"Working Pressure [mTorr]", None))
        self.ch1_forP_label.setText(QCoreApplication.translate("Form", u"For .P", None))
        self.ch1_processList_label.setText(QCoreApplication.translate("Form", u"Process List", None))
        self.ch1_rgaGraph_label.setText(QCoreApplication.translate("Form", u"RGA Graph", None))
        self.ch1_Stop_button.setText(QCoreApplication.translate("Form", u"STOP", None))
        self.ch1_gunTargetName_label.setText(QCoreApplication.translate("Form", u"Gun Target Name", None))
        self.ch1_Start_button.setText(QCoreApplication.translate("Form", u"START", None))
        self.ch1_refP_label.setText(QCoreApplication.translate("Form", u"Ref. P", None))
        self.ch1_processTime_label.setText(QCoreApplication.translate("Form", u"Process Time [min]", None))
        self.ch1_oesGraph_label.setText(QCoreApplication.translate("Form", u"OES Graph", None))
        self.ch1_O2_checkbox.setText(QCoreApplication.translate("Form", u"O2", None))
        self.ch1_logMessage_label.setText(QCoreApplication.translate("Form", u"Log Message", None))
        self.ch1_processState_edit.setPlainText("")
        self.ch1_btnGoPC.setText(QCoreApplication.translate("Form", u"Plasma\n"
"Cleaning", None))
        self.ch1_btnGoCh2.setText(QCoreApplication.translate("Form", u"CH.2", None))
        self.ch2_O2_checkbox.setText(QCoreApplication.translate("Form", u"O2", None))
        self.ch2_Voltage_label.setText(QCoreApplication.translate("Form", u"Voltage", None))
        self.ch2_Ar_checkbox.setText(QCoreApplication.translate("Form", u"Ar", None))
        self.ch2_oesGraph_label.setText(QCoreApplication.translate("Form", u"OES Graph", None))
        self.ch2_shutterDelay_label.setText(QCoreApplication.translate("Form", u"Shutter Delay [min]", None))
        self.ch2_rgaGraph_label.setText(QCoreApplication.translate("Form", u"RGA Graph", None))
        self.ch2_N2_checkbox.setText(QCoreApplication.translate("Form", u"N2", None))
        self.ch2_basePressure_label.setText(QCoreApplication.translate("Form", u"Base Pressure [Torr]", None))
        self.ch2_rfPulseDutyCycle_label.setText(QCoreApplication.translate("Form", u"RF Pulse Duty Cycle [%]", None))
        self.ch2_powerSelect_checkbox.setText(QCoreApplication.translate("Form", u"P.W. Select", None))
        self.ch2_workingPressure_label.setText(QCoreApplication.translate("Form", u"Working Pressure [mTorr]", None))
        self.ch2_processTime_label.setText(QCoreApplication.translate("Form", u"Process Time [min]", None))
        self.ch2_gasFlow_label.setText(QCoreApplication.translate("Form", u"Gas Flow [sccm]", None))
        self.ch2_forP_label.setText(QCoreApplication.translate("Form", u"For. P", None))
        self.ch2_Start_button.setText(QCoreApplication.translate("Form", u"START", None))
        self.ch2_G2_checkbox.setText(QCoreApplication.translate("Form", u"G2", None))
        self.ch2_G3_checkbox.setText(QCoreApplication.translate("Form", u"G3", None))
        self.ch2_integrationTime_label.setText(QCoreApplication.translate("Form", u"Integration Time [ms]", None))
        self.ch2_processList_button.setText(QCoreApplication.translate("Form", u"Select File", None))
        self.ch2_mainShutter_checkbox.setText(QCoreApplication.translate("Form", u"M.S. Open", None))
        self.ch2_rfPulseFreq_label.setText(QCoreApplication.translate("Form", u"RF Pulse Freq [kHz]", None))
        self.ch2_gunTargetName_label.setText(QCoreApplication.translate("Form", u"Gun Target Name", None))
        self.ch2_G1_checkbox.setText(QCoreApplication.translate("Form", u"G1", None))
        self.ch2_refP_label.setText(QCoreApplication.translate("Form", u"Ref. P", None))
        self.ch2_Stop_button.setText(QCoreApplication.translate("Form", u"STOP", None))
        self.ch2_processList_label.setText(QCoreApplication.translate("Form", u"Process List", None))
        self.ch2_Sputtering_label.setText(QCoreApplication.translate("Form", u"CH.2 Sputtering", None))
        self.ch2_Power_label.setText(QCoreApplication.translate("Form", u"Power", None))
        self.ch2_Current_label.setText(QCoreApplication.translate("Form", u"Current", None))
        self.ch2_rfPulsePower_checkbox.setText(QCoreApplication.translate("Form", u"RF Pulse Power [W]", None))
        self.ch2_logMessage_label.setText(QCoreApplication.translate("Form", u"Log Message", None))
        self.ch2_processState_edit.setPlainText("")
        self.ch2_btnGoPC.setText(QCoreApplication.translate("Form", u"Plasma\n"
"Cleaning", None))
        self.ch2_btnGoCh1.setText(QCoreApplication.translate("Form", u"CH.1", None))
        self.ch2_dcPower_checkbox.setText(QCoreApplication.translate("Form", u"DC Power", None))
        self.ch2_rfPower_checkbox.setText(QCoreApplication.translate("Form", u"RF Power", None))
    # retranslateUi

